begin;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.usuario (
  id uuid primary key references auth.users(id) on delete cascade,
  nome text not null,
  email text not null,
  telefone text,
  perfil text not null default 'Usuário'
    check (perfil in ('Gestor', 'Analista', 'Usuário')),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists usuario_email_lower_uidx
  on public.usuario (lower(email));

create table if not exists public.matriz (
  id integer generated by default as identity primary key,
  nome text not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists matriz_nome_lower_uidx
  on public.matriz (lower(nome));

create table if not exists public.legislacao (
  id integer generated by default as identity primary key,
  nome text not null,
  sigla text not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists legislacao_sigla_lower_uidx
  on public.legislacao (lower(sigla));

create table if not exists public.parametro (
  id integer generated by default as identity primary key,
  nome text not null,
  unidade_medida text not null default '',
  valor_parametro numeric(18, 6),
  limite_minimo numeric(18, 6),
  limite_maximo numeric(18, 6),
  matriz_id integer not null references public.matriz(id) on update cascade on delete restrict,
  legislacao_id integer not null references public.legislacao(id) on update cascade on delete restrict,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint parametro_limites_validos check (
    limite_minimo is null
    or limite_maximo is null
    or limite_minimo <= limite_maximo
  )
);

create unique index if not exists parametro_contexto_uidx
  on public.parametro (lower(nome), matriz_id, legislacao_id);
create index if not exists parametro_matriz_idx on public.parametro (matriz_id);
create index if not exists parametro_legislacao_idx on public.parametro (legislacao_id);

create table if not exists public.amostra (
  id integer generated by default as identity primary key,
  codigo_amostra text not null unique,
  numero_da_amostra text not null unique,
  data_coleta timestamptz not null,
  localizacao text,
  matriz_id integer not null references public.matriz(id) on update cascade on delete restrict,
  usuario_id uuid not null references public.usuario(id) on update cascade on delete restrict,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists amostra_matriz_idx on public.amostra (matriz_id);
create index if not exists amostra_usuario_idx on public.amostra (usuario_id);
create index if not exists amostra_data_coleta_idx on public.amostra (data_coleta desc);

create table if not exists public.amostra_parametro (
  amostra_id integer not null references public.amostra(id) on update cascade on delete cascade,
  parametro_id integer not null references public.parametro(id) on update cascade on delete restrict,
  created_at timestamptz not null default timezone('utc', now()),
  primary key (amostra_id, parametro_id)
);

create index if not exists amostra_parametro_parametro_idx
  on public.amostra_parametro (parametro_id);

create table if not exists public.resultado_analise (
  id integer generated by default as identity primary key,
  valor_medido numeric(18, 6) not null check (valor_medido >= 0),
  amostra_id integer not null references public.amostra(id) on update cascade on delete cascade,
  parametro_id integer not null references public.parametro(id) on update cascade on delete restrict,
  datacoleta timestamptz not null,
  datadapublicacao timestamptz not null default timezone('utc', now()),
  codigodaamostra text not null,
  numerodaamostra text not null,
  matriz text not null,
  legislacao text not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists resultado_amostra_idx
  on public.resultado_analise (amostra_id);
create index if not exists resultado_parametro_idx
  on public.resultado_analise (parametro_id);
create index if not exists resultado_datacoleta_idx
  on public.resultado_analise (datacoleta desc);
create index if not exists resultado_publicacao_idx
  on public.resultado_analise (datadapublicacao desc);
create index if not exists resultado_created_at_idx
  on public.resultado_analise (created_at desc);
create index if not exists resultado_parametro_data_idx
  on public.resultado_analise (parametro_id, datacoleta desc);

drop trigger if exists set_usuario_updated_at on public.usuario;
create trigger set_usuario_updated_at
before update on public.usuario
for each row execute function public.set_updated_at();

drop trigger if exists set_matriz_updated_at on public.matriz;
create trigger set_matriz_updated_at
before update on public.matriz
for each row execute function public.set_updated_at();

drop trigger if exists set_legislacao_updated_at on public.legislacao;
create trigger set_legislacao_updated_at
before update on public.legislacao
for each row execute function public.set_updated_at();

drop trigger if exists set_parametro_updated_at on public.parametro;
create trigger set_parametro_updated_at
before update on public.parametro
for each row execute function public.set_updated_at();

drop trigger if exists set_amostra_updated_at on public.amostra;
create trigger set_amostra_updated_at
before update on public.amostra
for each row execute function public.set_updated_at();

drop trigger if exists set_resultado_updated_at on public.resultado_analise;
create trigger set_resultado_updated_at
before update on public.resultado_analise
for each row execute function public.set_updated_at();

create or replace function public.sync_auth_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  perfil_administrativo text;
begin
  perfil_administrativo := case
    when new.raw_app_meta_data ->> 'perfil' in ('Gestor', 'Analista', 'Usuário')
      then new.raw_app_meta_data ->> 'perfil'
    else null
  end;

  insert into public.usuario (id, nome, email, telefone, perfil)
  values (
    new.id,
    coalesce(
      nullif(trim(new.raw_user_meta_data ->> 'nome'), ''),
      nullif(trim(new.raw_user_meta_data ->> 'full_name'), ''),
      split_part(new.email, '@', 1)
    ),
    new.email,
    nullif(trim(new.raw_user_meta_data ->> 'telefone'), ''),
    coalesce(perfil_administrativo, 'Usuário')
  )
  on conflict (id) do update
  set nome = excluded.nome,
      email = excluded.email,
      telefone = excluded.telefone,
      perfil = coalesce(perfil_administrativo, usuario.perfil);

  return new;
end;
$$;

drop trigger if exists sync_auth_user_profile on auth.users;
create trigger sync_auth_user_profile
after insert or update of email, raw_user_meta_data, raw_app_meta_data
on auth.users
for each row execute function public.sync_auth_user();

insert into public.usuario (id, nome, email, telefone, perfil)
select
  id,
  coalesce(
    nullif(trim(raw_user_meta_data ->> 'nome'), ''),
    nullif(trim(raw_user_meta_data ->> 'full_name'), ''),
    split_part(email, '@', 1)
  ),
  email,
  nullif(trim(raw_user_meta_data ->> 'telefone'), ''),
  case
    when raw_app_meta_data ->> 'perfil' in ('Gestor', 'Analista', 'Usuário')
      then raw_app_meta_data ->> 'perfil'
    else 'Usuário'
  end
from auth.users
where email is not null
on conflict (id) do nothing;

alter table public.usuario enable row level security;
alter table public.matriz enable row level security;
alter table public.legislacao enable row level security;
alter table public.parametro enable row level security;
alter table public.amostra enable row level security;
alter table public.amostra_parametro enable row level security;
alter table public.resultado_analise enable row level security;

revoke all on table public.usuario from anon, authenticated;
revoke all on table public.matriz from anon, authenticated;
revoke all on table public.legislacao from anon, authenticated;
revoke all on table public.parametro from anon, authenticated;
revoke all on table public.amostra from anon, authenticated;
revoke all on table public.amostra_parametro from anon, authenticated;
revoke all on table public.resultado_analise from anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;
revoke execute on function public.set_updated_at() from public, anon, authenticated;
revoke execute on function public.sync_auth_user() from public, anon, authenticated;

commit;
