begin;

-- Cadastros comerciais mínimos para relacionar a solicitação, a amostra e o laudo.
create table if not exists public.cliente (
  id bigint generated by default as identity primary key,
  codigo text not null,
  nome_razao_social text not null,
  nome_fantasia text,
  documento text,
  email text,
  telefone text,
  endereco text,
  observacoes text,
  ativo boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  deleted_at timestamptz,
  deleted_by uuid references public.usuario(id) on update cascade on delete set null,
  deletion_reason text,
  constraint cliente_codigo_preenchido check (nullif(trim(codigo), '') is not null),
  constraint cliente_nome_preenchido check (nullif(trim(nome_razao_social), '') is not null)
);

create unique index if not exists cliente_codigo_lower_uidx
  on public.cliente (lower(codigo)) where deleted_at is null;
create unique index if not exists cliente_documento_lower_uidx
  on public.cliente (lower(documento))
  where documento is not null and nullif(trim(documento), '') is not null and deleted_at is null;
create index if not exists cliente_busca_idx
  on public.cliente (ativo, nome_razao_social) where deleted_at is null;

create table if not exists public.pedido_analise (
  id bigint generated by default as identity primary key,
  codigo text not null,
  cliente_id bigint not null references public.cliente(id) on update cascade on delete restrict,
  solicitante text,
  descricao text,
  prioridade text not null default 'normal'
    check (prioridade in ('normal', 'alta', 'urgente')),
  data_entrada timestamptz not null default timezone('utc', now()),
  prazo timestamptz,
  status text not null default 'rascunho'
    check (status in ('rascunho', 'recebido', 'em_execucao', 'concluido', 'cancelado')),
  observacoes text,
  created_by uuid references public.usuario(id) on update cascade on delete set null,
  status_updated_at timestamptz not null default timezone('utc', now()),
  status_updated_by uuid references public.usuario(id) on update cascade on delete set null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  deleted_at timestamptz,
  deleted_by uuid references public.usuario(id) on update cascade on delete set null,
  deletion_reason text,
  constraint pedido_codigo_preenchido check (nullif(trim(codigo), '') is not null),
  constraint pedido_prazo_valido check (prazo is null or prazo >= data_entrada)
);

create unique index if not exists pedido_analise_codigo_lower_uidx
  on public.pedido_analise (lower(codigo)) where deleted_at is null;
create index if not exists pedido_analise_cliente_idx
  on public.pedido_analise (cliente_id, created_at desc) where deleted_at is null;
create index if not exists pedido_analise_status_idx
  on public.pedido_analise (status, prioridade, prazo) where deleted_at is null;

create table if not exists public.metodo_analitico (
  id bigint generated by default as identity primary key,
  codigo text not null,
  nome text not null,
  versao text not null,
  parametro_id integer references public.parametro(id) on update cascade on delete restrict,
  matriz_id integer references public.matriz(id) on update cascade on delete restrict,
  referencia_normativa text,
  principio text,
  procedimento_resumido text,
  unidade_resultado text,
  limite_deteccao numeric(18, 6),
  limite_quantificacao numeric(18, 6),
  incerteza_padrao numeric(18, 6),
  ativo boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint metodo_codigo_preenchido check (nullif(trim(codigo), '') is not null),
  constraint metodo_nome_preenchido check (nullif(trim(nome), '') is not null),
  constraint metodo_versao_preenchida check (nullif(trim(versao), '') is not null),
  constraint metodo_limites_nao_negativos check (
    (limite_deteccao is null or limite_deteccao >= 0)
    and (limite_quantificacao is null or limite_quantificacao >= 0)
    and (incerteza_padrao is null or incerteza_padrao >= 0)
  ),
  constraint metodo_ld_lq_consistentes check (
    limite_deteccao is null or limite_quantificacao is null
    or limite_deteccao <= limite_quantificacao
  )
);

create unique index if not exists metodo_codigo_versao_lower_uidx
  on public.metodo_analitico (lower(codigo), lower(versao));
create index if not exists metodo_parametro_idx
  on public.metodo_analitico (parametro_id, ativo, nome);
create index if not exists metodo_matriz_idx
  on public.metodo_analitico (matriz_id, ativo, nome);

alter table public.amostra
  add column if not exists pedido_analise_id bigint references public.pedido_analise(id) on update cascade on delete restrict,
  add column if not exists status_amostra text,
  add column if not exists status_atualizado_em timestamptz,
  add column if not exists status_atualizado_por uuid references public.usuario(id) on update cascade on delete set null,
  add column if not exists local_atual text;

update public.amostra
set status_amostra = coalesce(status_amostra, 'recebida'),
    status_atualizado_em = coalesce(status_atualizado_em, created_at),
    local_atual = coalesce(local_atual, localizacao)
where status_amostra is null or status_atualizado_em is null or local_atual is null;

alter table public.amostra
  alter column status_amostra set default 'recebida',
  alter column status_amostra set not null,
  alter column status_atualizado_em set default timezone('utc', now()),
  alter column status_atualizado_em set not null;

alter table public.amostra drop constraint if exists amostra_status_amostra_check;
alter table public.amostra add constraint amostra_status_amostra_check
  check (status_amostra in (
    'recebida', 'em_triagem', 'em_analise', 'aguardando_revisao',
    'concluida', 'rejeitada', 'cancelada'
  ));

create index if not exists amostra_pedido_idx
  on public.amostra (pedido_analise_id, created_at desc) where deleted_at is null;
create index if not exists amostra_status_idx
  on public.amostra (status_amostra, status_atualizado_em desc) where deleted_at is null;

alter table public.amostra_parametro
  add column if not exists metodo_analitico_id bigint
    references public.metodo_analitico(id) on update cascade on delete restrict;

-- A cadeia de custódia é append-only; o estado atual também permanece na amostra
-- para consultas eficientes, mas cada mudança deve gerar um evento nesta tabela.
create table if not exists public.amostra_custodia_evento (
  id bigint generated by default as identity primary key,
  amostra_id integer not null references public.amostra(id) on update cascade on delete restrict,
  tipo_evento text not null check (tipo_evento in (
    'recebimento', 'aceite', 'rejeicao', 'movimentacao', 'armazenamento',
    'retirada', 'descarte', 'status'
  )),
  status_anterior text,
  status_novo text,
  local_origem text,
  local_destino text,
  observacao text,
  ocorrido_em timestamptz not null default timezone('utc', now()),
  actor_user_id uuid references public.usuario(id) on update cascade on delete set null,
  request_id uuid,
  created_at timestamptz not null default timezone('utc', now()),
  constraint custodia_status_preenchido check (
    tipo_evento <> 'status'
    or (status_anterior is not null and status_novo is not null)
  )
);

create index if not exists custodia_amostra_data_idx
  on public.amostra_custodia_evento (amostra_id, ocorrido_em desc, id desc);
create index if not exists custodia_actor_data_idx
  on public.amostra_custodia_evento (actor_user_id, ocorrido_em desc);

insert into public.amostra_custodia_evento (
  amostra_id, tipo_evento, status_novo, local_destino, observacao, ocorrido_em, actor_user_id
)
select a.id, 'recebimento', a.status_amostra, coalesce(a.local_atual, a.localizacao),
       'Evento inicial criado na migração do fluxo piloto.', a.created_at, a.usuario_id
from public.amostra a
where not exists (
  select 1 from public.amostra_custodia_evento e where e.amostra_id = a.id
);

-- Assinaturas registram somente evidências da reautenticação. Senhas e tokens
-- nunca são persistidos.
create table if not exists public.assinatura_eletronica (
  id bigint generated by default as identity primary key,
  signer_user_id uuid not null references public.usuario(id) on update cascade on delete restrict,
  entity_type text not null,
  entity_id text not null,
  action text not null check (action in ('APPROVE', 'REJECT', 'PUBLISH', 'REOPEN', 'REPORT_ISSUE')),
  auth_method text not null check (auth_method in ('supabase_password')),
  authenticated_at timestamptz not null,
  signed_at timestamptz not null default timezone('utc', now()),
  entity_version integer,
  status_origem text,
  status_destino text,
  payload_hash text not null check (payload_hash ~ '^[0-9a-f]{64}$'),
  ip_address text,
  user_agent text,
  request_id uuid,
  metadata jsonb not null default '{}'::jsonb,
  constraint assinatura_temporal_valida_check check (
    authenticated_at <= signed_at
    and signed_at <= authenticated_at + interval '5 minutes'
  ),
  constraint assinatura_entity_version_positiva_check check (
    entity_version is null or entity_version > 0
  )
);

alter table public.assinatura_eletronica
  add column if not exists entity_version integer,
  add column if not exists status_origem text,
  add column if not exists status_destino text;

alter table public.assinatura_eletronica
  drop constraint if exists assinatura_temporal_valida_check;
alter table public.assinatura_eletronica
  add constraint assinatura_temporal_valida_check check (
    authenticated_at <= signed_at
    and signed_at <= authenticated_at + interval '5 minutes'
  );
alter table public.assinatura_eletronica
  drop constraint if exists assinatura_entity_version_positiva_check;
alter table public.assinatura_eletronica
  add constraint assinatura_entity_version_positiva_check check (
    entity_version is null or entity_version > 0
  );

create unique index if not exists assinatura_payload_hash_uidx
  on public.assinatura_eletronica (payload_hash);
create index if not exists assinatura_entidade_idx
  on public.assinatura_eletronica (entity_type, entity_id, signed_at desc);

alter table public.assinatura_eletronica
  drop constraint if exists assinatura_eletronica_action_check;
alter table public.assinatura_eletronica
  add constraint assinatura_eletronica_action_check
  check (action in ('APPROVE', 'REJECT', 'PUBLISH', 'REOPEN', 'REPORT_ISSUE'));

alter table public.resultado_analise
  add column if not exists metodo_analitico_id bigint references public.metodo_analitico(id) on update cascade on delete restrict,
  add column if not exists snapshot_analitico jsonb,
  add column if not exists status_resultado text,
  add column if not exists versao integer,
  add column if not exists submetido_em timestamptz,
  add column if not exists submetido_por uuid references public.usuario(id) on update cascade on delete set null,
  add column if not exists aprovado_em timestamptz,
  add column if not exists aprovado_por uuid references public.usuario(id) on update cascade on delete set null,
  add column if not exists rejeitado_em timestamptz,
  add column if not exists rejeitado_por uuid references public.usuario(id) on update cascade on delete set null,
  add column if not exists publicado_em timestamptz,
  add column if not exists publicado_por uuid references public.usuario(id) on update cascade on delete set null,
  add column if not exists ultimo_comentario text,
  add column if not exists parametro_nome_aplicado text,
  add column if not exists unidade_medida_aplicada text,
  add column if not exists metodo_snapshot jsonb,
  add column if not exists ultima_assinatura_eletronica_id bigint;

alter table public.resultado_analise
  drop constraint if exists resultado_analise_ultima_assinatura_eletronica_id_fkey;
alter table public.resultado_analise
  drop constraint if exists resultado_ultima_assinatura_eletronica_fk;
alter table public.resultado_analise
  add constraint resultado_ultima_assinatura_eletronica_fk
  foreign key (ultima_assinatura_eletronica_id)
  references public.assinatura_eletronica(id)
  on update cascade on delete restrict;

-- Repara vínculos e duplicidades que eram aceitos pelo esquema anterior antes
-- de criar as novas restrições. Nenhuma linha histórica é removida fisicamente.
insert into public.amostra_parametro (amostra_id, parametro_id)
select distinct ra.amostra_id, ra.parametro_id
from public.resultado_analise ra
on conflict (amostra_id, parametro_id) do nothing;

with ranked as (
  select ra.id,
         row_number() over (
           partition by ra.amostra_id, ra.parametro_id
           order by coalesce(ra.datadapublicacao, ra.created_at) desc, ra.id desc
         ) as position
  from public.resultado_analise ra
  where ra.deleted_at is null
), archived as (
  update public.resultado_analise ra
  set deleted_at = timezone('utc', now()),
      deletion_reason = coalesce(
        ra.deletion_reason,
        'Duplicidade legada arquivada na implantação do workflow piloto.'
      )
  from ranked r
  where ra.id = r.id and r.position > 1
  returning ra.*
)
insert into public.audit_log (
  action, entity_type, entity_id, before_data, after_data, metadata
)
select 'ARCHIVE', 'resultado_analise', a.id::text, null, to_jsonb(a),
       jsonb_build_object('origem', 'migracao_piloto', 'motivo', 'duplicidade_legada')
from archived a;

update public.resultado_analise ra
set parametro_nome_aplicado = coalesce(ra.parametro_nome_aplicado, p.nome),
    unidade_medida_aplicada = coalesce(ra.unidade_medida_aplicada, p.unidade_medida)
from public.parametro p
where p.id = ra.parametro_id
  and (ra.parametro_nome_aplicado is null or ra.unidade_medida_aplicada is null);

-- Resultados anteriores não possuem revisão nem assinatura verificável. Eles
-- entram como rascunho legado e precisam percorrer o workflow antes de um laudo.
update public.resultado_analise
set status_resultado = coalesce(status_resultado, 'rascunho'),
    versao = coalesce(versao, 1),
    publicado_em = case when status_resultado = 'publicado'
      then coalesce(publicado_em, datadapublicacao, created_at)
      else null
    end,
    publicado_por = case when status_resultado = 'publicado' then publicado_por else null end
where status_resultado is null or versao is null
   or (status_resultado = 'publicado' and publicado_em is null);

-- Congela o contexto analítico dos resultados legados. Novas versões são criadas
-- pela API com a mesma estrutura e nunca dependem do cadastro mutável no laudo.
update public.resultado_analise ra
set snapshot_analitico = (
  select jsonb_build_object(
    'schema_version', 1,
    'versao_resultado', coalesce(ra.versao, 1),
    'valor_medido', ra.valor_medido,
    'valor_qualitativo', ra.valor_qualitativo,
    'datacoleta', ra.datacoleta,
    'parametro', jsonb_build_object(
      'id', p.id,
      'nome', p.nome,
      'unidade_medida', p.unidade_medida,
      'tipo_resultado', p.tipo_resultado,
      'categoria', p.categoria
    ),
    'matriz', jsonb_build_object('id', m.id, 'nome', m.nome),
    'referencia_legal', jsonb_build_object(
      'legislacao_id', l.id,
      'legislacao_nome', l.nome,
      'legislacao_sigla', l.sigla,
      'contexto_id', lc.id,
      'contexto_codigo', lc.codigo,
      'contexto_nome', lc.nome,
      'limite_minimo', coalesce(ra.limite_minimo_aplicado, p.limite_minimo),
      'limite_maximo', coalesce(ra.limite_maximo_aplicado, p.limite_maximo),
      'tipo_limite', coalesce(ra.tipo_limite_aplicado, p.tipo_limite),
      'criterio', coalesce(ra.criterio_legal_aplicado, p.criterio_texto),
      'fonte', coalesce(ra.fonte_legal_aplicada, p.fonte_referencia)
    ),
    'metodo', case when ma.id is null then null else jsonb_build_object(
      'id', ma.id,
      'codigo', ma.codigo,
      'nome', ma.nome,
      'versao', ma.versao,
      'referencia_normativa', ma.referencia_normativa,
      'unidade_resultado', ma.unidade_resultado,
      'limite_deteccao', ma.limite_deteccao,
      'limite_quantificacao', ma.limite_quantificacao,
      'incerteza_padrao', ma.incerteza_padrao
    ) end,
    'legado_sem_assinatura', true,
    'publicacao_legada_em', ra.datadapublicacao
  )
  from public.parametro p
  join public.amostra a on a.id = ra.amostra_id
  join public.matriz m on m.id = a.matriz_id
  join public.legislacao l on l.id = p.legislacao_id
  join public.legislacao_contexto lc on lc.id = p.contexto_legislacao_id
  left join public.metodo_analitico ma on ma.id = ra.metodo_analitico_id
  where p.id = ra.parametro_id
)
where ra.snapshot_analitico is null;

update public.resultado_analise
set datadapublicacao = null
where status_resultado = 'rascunho' and publicado_em is null;

alter table public.resultado_analise
  alter column status_resultado set default 'rascunho',
  alter column status_resultado set not null,
  alter column versao set default 1,
  alter column versao set not null,
  alter column snapshot_analitico set not null,
  alter column datadapublicacao drop not null,
  alter column datadapublicacao drop default;

alter table public.resultado_analise drop constraint if exists resultado_status_resultado_check;
alter table public.resultado_analise add constraint resultado_status_resultado_check
  check (status_resultado in ('rascunho', 'em_revisao', 'aprovado', 'rejeitado', 'publicado'));
alter table public.resultado_analise drop constraint if exists resultado_versao_positiva_check;
alter table public.resultado_analise add constraint resultado_versao_positiva_check check (versao > 0);
alter table public.resultado_analise drop constraint if exists resultado_amostra_parametro_fk;
alter table public.resultado_analise add constraint resultado_amostra_parametro_fk
  foreign key (amostra_id, parametro_id)
  references public.amostra_parametro (amostra_id, parametro_id)
  on update cascade on delete restrict;

create index if not exists resultado_workflow_idx
  on public.resultado_analise (status_resultado, updated_at desc) where deleted_at is null;
create index if not exists resultado_metodo_idx
  on public.resultado_analise (metodo_analitico_id, datacoleta desc) where deleted_at is null;
create index if not exists resultado_ultima_assinatura_idx
  on public.resultado_analise (ultima_assinatura_eletronica_id)
  where ultima_assinatura_eletronica_id is not null;
create unique index if not exists resultado_amostra_parametro_active_uidx
  on public.resultado_analise (amostra_id, parametro_id) where deleted_at is null;

-- Cada edicao cria uma nova versao append-only do conteudo analitico. A coluna
-- na tabela principal representa somente a versao corrente.
create table if not exists public.resultado_versao_snapshot (
  id bigint generated by default as identity primary key,
  resultado_id integer not null references public.resultado_analise(id) on update cascade on delete restrict,
  versao integer not null check (versao > 0),
  snapshot_analitico jsonb not null,
  criado_em timestamptz not null default timezone('utc', now()),
  criado_por uuid references public.usuario(id) on update cascade on delete set null,
  request_id uuid,
  unique (resultado_id, versao)
);

insert into public.resultado_versao_snapshot (
  resultado_id, versao, snapshot_analitico, criado_em
)
select ra.id, ra.versao, ra.snapshot_analitico, coalesce(ra.updated_at, ra.created_at)
from public.resultado_analise ra
on conflict (resultado_id, versao) do nothing;

create index if not exists resultado_versao_snapshot_resultado_idx
  on public.resultado_versao_snapshot (resultado_id, versao desc);

create table if not exists public.resultado_workflow_evento (
  id bigint generated by default as identity primary key,
  resultado_id integer not null references public.resultado_analise(id) on update cascade on delete restrict,
  status_anterior text,
  status_novo text not null,
  decisao text not null check (decisao in (
    'criacao', 'edicao', 'submissao', 'aprovacao', 'rejeicao', 'publicacao', 'reabertura'
  )),
  comentario text,
  actor_user_id uuid references public.usuario(id) on update cascade on delete set null,
  assinatura_eletronica_id bigint references public.assinatura_eletronica(id) on update cascade on delete restrict,
  resultado_versao integer,
  ocorrido_em timestamptz not null default timezone('utc', now()),
  request_id uuid,
  metadata jsonb not null default '{}'::jsonb
);

alter table public.resultado_workflow_evento
  add column if not exists resultado_versao integer;

create index if not exists resultado_workflow_resultado_idx
  on public.resultado_workflow_evento (resultado_id, ocorrido_em desc, id desc);
create unique index if not exists resultado_workflow_assinatura_uidx
  on public.resultado_workflow_evento (assinatura_eletronica_id)
  where assinatura_eletronica_id is not null;

insert into public.resultado_workflow_evento (
  resultado_id, status_anterior, status_novo, decisao, comentario,
  actor_user_id, resultado_versao, ocorrido_em, metadata
)
select ra.id, null, ra.status_resultado, 'criacao',
       'Histórico inicial reconstruído na implantação do workflow piloto.',
       null, ra.versao, ra.created_at,
       jsonb_build_object('origem', 'migracao_piloto', 'legado', true)
from public.resultado_analise ra
where not exists (
  select 1 from public.resultado_workflow_evento e where e.resultado_id = ra.id
);

-- Mantem compatibilidade com uma eventual execucao anterior desta migracao:
-- explicita a versao nos eventos e o contexto das assinaturas ja consumidas.
update public.resultado_workflow_evento event
set resultado_versao = coalesce(
  case
    when event.metadata ->> 'versao' ~ '^[1-9][0-9]*$'
      then (event.metadata ->> 'versao')::integer
    else null
  end,
  result.versao
)
from public.resultado_analise result
where result.id = event.resultado_id
  and event.resultado_versao is null;

update public.assinatura_eletronica signature
set entity_version = coalesce(signature.entity_version, event.resultado_versao),
    status_origem = coalesce(signature.status_origem, event.status_anterior),
    status_destino = coalesce(signature.status_destino, event.status_novo)
from public.resultado_workflow_evento event
where event.assinatura_eletronica_id = signature.id
  and signature.entity_type = 'resultado_analise'
  and signature.action in ('APPROVE', 'REJECT', 'PUBLISH', 'REOPEN')
  and (
    signature.entity_version is null
    or signature.status_origem is null
    or signature.status_destino is null
  );

with latest_signature as (
  select distinct on (event.resultado_id)
         event.resultado_id, event.assinatura_eletronica_id
  from public.resultado_workflow_evento event
  where event.assinatura_eletronica_id is not null
  order by event.resultado_id, event.ocorrido_em desc, event.id desc
)
update public.resultado_analise result
set ultima_assinatura_eletronica_id = latest.assinatura_eletronica_id
from latest_signature latest
where result.id = latest.resultado_id
  and result.ultima_assinatura_eletronica_id is null;

alter table public.resultado_workflow_evento
  alter column resultado_versao set not null;
alter table public.resultado_workflow_evento
  drop constraint if exists resultado_workflow_versao_positiva_check;
alter table public.resultado_workflow_evento
  add constraint resultado_workflow_versao_positiva_check
  check (resultado_versao > 0);

alter table public.assinatura_eletronica
  drop constraint if exists assinatura_resultado_contexto_check;
alter table public.assinatura_eletronica
  add constraint assinatura_resultado_contexto_check check (
    entity_type <> 'resultado_analise'
    or action not in ('APPROVE', 'REJECT', 'PUBLISH', 'REOPEN')
    or (
      entity_version is not null
      and status_origem is not null
      and status_destino is not null
      and (
        (action = 'APPROVE' and status_origem = 'em_revisao' and status_destino = 'aprovado')
        or (action = 'REJECT' and status_origem = 'em_revisao' and status_destino = 'rejeitado')
        or (action = 'PUBLISH' and status_origem = 'aprovado' and status_destino = 'publicado')
        or (action = 'REOPEN' and status_origem = 'aprovado' and status_destino = 'rascunho')
      )
    )
  );

-- Reconcilia amostras legadas com seus resultados e registra cada mudança na
-- cadeia de custódia, sem reabrir amostras que já possuíam estado terminal.
with desired as (
  select a.id,
         a.status_amostra as previous_status,
         case
           when count(ra.id) filter (where ra.deleted_at is null) = 0
             then a.status_amostra
           when bool_and(ra.status_resultado = 'publicado')
                filter (where ra.deleted_at is null)
             then 'concluida'
           else 'em_analise'
         end as next_status,
         a.local_atual
  from public.amostra a
  left join public.resultado_analise ra on ra.amostra_id = a.id
  where a.deleted_at is null
  group by a.id
), changed as (
  update public.amostra a
  set status_amostra = d.next_status,
      status_atualizado_em = timezone('utc', now()),
      status_atualizado_por = null
  from desired d
  where a.id = d.id
    and d.previous_status in ('recebida','em_triagem','em_analise','aguardando_revisao')
    and d.previous_status <> d.next_status
  returning a.id, d.previous_status, d.next_status, d.local_atual
)
insert into public.amostra_custodia_evento (
  amostra_id, tipo_evento, status_anterior, status_novo,
  local_origem, local_destino, observacao, actor_user_id
)
select id, 'status', previous_status, next_status, local_atual, local_atual,
       'Estado reconciliado automaticamente na implantação do workflow piloto.', null
from changed;

create table if not exists public.laudo_analitico (
  id bigint generated by default as identity primary key,
  numero text not null unique,
  amostra_id integer not null references public.amostra(id) on update cascade on delete restrict,
  pedido_analise_id bigint references public.pedido_analise(id) on update cascade on delete restrict,
  versao integer not null check (versao > 0),
  snapshot jsonb not null,
  conteudo_hash text not null check (conteudo_hash ~ '^[0-9a-f]{64}$'),
  observacoes text,
  motivo_revisao text,
  emitido_por uuid not null references public.usuario(id) on update cascade on delete restrict,
  assinatura_eletronica_id bigint not null references public.assinatura_eletronica(id) on update cascade on delete restrict,
  emitido_em timestamptz not null default timezone('utc', now()),
  request_id uuid,
  unique (amostra_id, versao)
);

create index if not exists laudo_amostra_idx
  on public.laudo_analitico (amostra_id, versao desc);
create index if not exists laudo_pedido_idx
  on public.laudo_analitico (pedido_analise_id, emitido_em desc);
create unique index if not exists laudo_conteudo_hash_uidx
  on public.laudo_analitico (conteudo_hash);
create unique index if not exists laudo_assinatura_eletronica_uidx
  on public.laudo_analitico (assinatura_eletronica_id);

alter table public.laudo_analitico drop constraint if exists laudo_motivo_revisao_check;
alter table public.laudo_analitico add constraint laudo_motivo_revisao_check check (
  versao = 1 or nullif(trim(motivo_revisao), '') is not null
);

-- Amplia o vocabulário da trilha central sem remover os eventos anteriores.
alter table public.audit_log drop constraint if exists audit_log_action_check;
alter table public.audit_log add constraint audit_log_action_check check (action in (
  'CREATE', 'UPDATE', 'ARCHIVE', 'RESTORE', 'IMPORT', 'ROLE_CHANGE',
  'SUBMIT', 'APPROVE', 'REJECT', 'PUBLISH', 'REOPEN', 'STATUS_CHANGE',
  'CUSTODY_EVENT', 'REPORT_GENERATE'
));

drop trigger if exists set_cliente_updated_at on public.cliente;
create trigger set_cliente_updated_at before update on public.cliente
for each row execute function public.set_updated_at();
drop trigger if exists set_pedido_analise_updated_at on public.pedido_analise;
create trigger set_pedido_analise_updated_at before update on public.pedido_analise
for each row execute function public.set_updated_at();
drop trigger if exists set_metodo_analitico_updated_at on public.metodo_analitico;
create trigger set_metodo_analitico_updated_at before update on public.metodo_analitico
for each row execute function public.set_updated_at();

create or replace function public.prevent_pilot_append_only_mutation()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  raise exception 'Este registro é append-only e não pode ser alterado ou removido';
end;
$$;

create or replace function public.prevent_referenced_method_content_update()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if exists (
    select 1
    from public.resultado_analise ra
    where ra.metodo_analitico_id = old.id
  ) and (
    old.codigo is distinct from new.codigo
    or old.nome is distinct from new.nome
    or old.versao is distinct from new.versao
    or old.parametro_id is distinct from new.parametro_id
    or old.matriz_id is distinct from new.matriz_id
    or old.referencia_normativa is distinct from new.referencia_normativa
    or old.principio is distinct from new.principio
    or old.procedimento_resumido is distinct from new.procedimento_resumido
    or old.unidade_resultado is distinct from new.unidade_resultado
    or old.limite_deteccao is distinct from new.limite_deteccao
    or old.limite_quantificacao is distinct from new.limite_quantificacao
    or old.incerteza_padrao is distinct from new.incerteza_padrao
  ) then
    raise exception 'Metodo referenciado por resultado: crie uma nova versao em vez de altera-lo';
  end if;
  return new;
end;
$$;

create or replace function public.bind_assinatura_context()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  current_version integer;
  current_status text;
  expected_destination text;
  metadata_version integer;
begin
  if new.authenticated_at > new.signed_at
     or new.signed_at > new.authenticated_at + interval '5 minutes' then
    raise exception 'Janela temporal da assinatura eletronica invalida';
  end if;

  if new.signed_at < clock_timestamp() - interval '5 minutes'
     or new.signed_at > clock_timestamp() + interval '30 seconds' then
    raise exception 'Assinatura eletronica expirada ou com data futura';
  end if;

  if new.entity_type = 'resultado_analise'
     and new.action in ('APPROVE', 'REJECT', 'PUBLISH', 'REOPEN') then
    if new.entity_id !~ '^[1-9][0-9]*$' or length(new.entity_id) > 10 then
      raise exception 'Identificador de resultado invalido na assinatura eletronica';
    end if;

    select result.versao, result.status_resultado
      into current_version, current_status
    from public.resultado_analise result
    where result.id = new.entity_id::bigint
      and result.deleted_at is null;

    if not found then
      raise exception 'Resultado da assinatura eletronica nao encontrado';
    end if;

    expected_destination := case
      when new.action = 'APPROVE' and current_status = 'em_revisao' then 'aprovado'
      when new.action = 'REJECT' and current_status = 'em_revisao' then 'rejeitado'
      when new.action = 'PUBLISH' and current_status = 'aprovado' then 'publicado'
      when new.action = 'REOPEN' and current_status = 'aprovado' then 'rascunho'
      else null
    end;

    if expected_destination is null then
      raise exception 'Acao de assinatura incompativel com o estado atual do resultado';
    end if;

    if coalesce(new.metadata ->> 'entity_version', '') !~ '^[1-9][0-9]*$' then
      raise exception 'Versao do resultado ausente na assinatura eletronica';
    end if;
    metadata_version := (new.metadata ->> 'entity_version')::integer;

    if metadata_version <> current_version
       or new.metadata ->> 'status_origin' is distinct from current_status
       or new.metadata ->> 'status_destination' is distinct from expected_destination then
      raise exception 'Contexto da assinatura nao corresponde a transicao do resultado';
    end if;

    if new.entity_version is not null and new.entity_version <> current_version then
      raise exception 'Versao estrutural da assinatura diverge do resultado';
    end if;
    if new.status_origem is not null and new.status_origem is distinct from current_status then
      raise exception 'Estado de origem estrutural da assinatura diverge do resultado';
    end if;
    if new.status_destino is not null and new.status_destino is distinct from expected_destination then
      raise exception 'Estado de destino estrutural da assinatura diverge do resultado';
    end if;

    new.entity_version := current_version;
    new.status_origem := current_status;
    new.status_destino := expected_destination;
  end if;

  return new;
end;
$$;

create or replace function public.protect_resultado_workflow_content()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  required_action text;
  required_actor uuid;
  matching_signature_id bigint;
  matching_signature_count integer;
begin
  if tg_op = 'DELETE' then
    if old.status_resultado in ('em_revisao', 'aprovado', 'publicado') then
      raise exception 'Resultado em revisão, aprovado ou publicado não pode ser removido';
    end if;
    return old;
  end if;

  if old.status_resultado = 'publicado' then
    raise exception 'Resultado publicado é imutável';
  end if;

  if old.status_resultado is distinct from new.status_resultado and not (
    (old.status_resultado = 'rascunho' and new.status_resultado = 'em_revisao')
    or (old.status_resultado = 'em_revisao' and new.status_resultado in ('aprovado', 'rejeitado'))
    or (old.status_resultado = 'rejeitado' and new.status_resultado = 'rascunho')
    or (old.status_resultado = 'aprovado' and new.status_resultado in ('rascunho', 'publicado'))
  ) then
    raise exception 'Transição inválida do workflow de resultado: % para %',
      old.status_resultado, new.status_resultado;
  end if;

  required_action := case
    when old.status_resultado = 'em_revisao' and new.status_resultado = 'aprovado'
      then 'APPROVE'
    when old.status_resultado = 'em_revisao' and new.status_resultado = 'rejeitado'
      then 'REJECT'
    when old.status_resultado = 'aprovado' and new.status_resultado = 'publicado'
      then 'PUBLISH'
    when old.status_resultado = 'aprovado' and new.status_resultado = 'rascunho'
      then 'REOPEN'
    else null
  end;

  required_actor := case required_action
    when 'APPROVE' then new.aprovado_por
    when 'REJECT' then new.rejeitado_por
    when 'PUBLISH' then new.publicado_por
    else null
  end;

  if required_action is not null then
    select count(*)::integer, min(signature.id)
      into matching_signature_count, matching_signature_id
    from public.assinatura_eletronica signature
    where signature.entity_type = 'resultado_analise'
      and signature.entity_id = new.id::text
      and signature.action = required_action
      and (required_actor is null or signature.signer_user_id = required_actor)
      and signature.entity_version = old.versao
      and signature.entity_version = new.versao
      and signature.status_origem = old.status_resultado
      and signature.status_destino = new.status_resultado
      and signature.authenticated_at <= signature.signed_at
      and signature.signed_at <= signature.authenticated_at + interval '5 minutes'
      and signature.signed_at >= clock_timestamp() - interval '5 minutes'
      and signature.signed_at <= clock_timestamp() + interval '30 seconds'
      and signature.id is distinct from old.ultima_assinatura_eletronica_id
      and not exists (
        select 1
        from public.resultado_workflow_evento used_event
        where used_event.assinatura_eletronica_id = signature.id
      );

    if matching_signature_count <> 1 then
      raise exception 'A transicao exige exatamente uma assinatura nova e ainda nao utilizada';
    end if;

    if new.ultima_assinatura_eletronica_id is not null
       and new.ultima_assinatura_eletronica_id <> matching_signature_id then
      raise exception 'A assinatura indicada nao corresponde a transicao do resultado';
    end if;
    new.ultima_assinatura_eletronica_id := matching_signature_id;
  elsif new.ultima_assinatura_eletronica_id is distinct from old.ultima_assinatura_eletronica_id then
    raise exception 'A ultima assinatura so pode mudar em uma transicao assinada';
  end if;

  if new.status_resultado = 'em_revisao'
     and old.status_resultado is distinct from new.status_resultado
     and (
       new.metodo_analitico_id is null
       or jsonb_typeof(new.snapshot_analitico -> 'metodo') is distinct from 'object'
     ) then
    raise exception 'Método e snapshot analítico são obrigatórios para revisão';
  end if;

  if new.status_resultado = 'aprovado'
     and old.status_resultado is distinct from new.status_resultado then
    if new.aprovado_por is null or new.aprovado_por = old.submetido_por then
      raise exception 'Aprovação exige revisor diferente do responsável pela submissão';
    end if;
  end if;

  if new.status_resultado = 'rejeitado'
     and old.status_resultado is distinct from new.status_resultado then
    if new.rejeitado_por is null or new.rejeitado_por = old.submetido_por then
      raise exception 'Rejeição exige revisor diferente do responsável pela submissão';
    end if;
  end if;

  if old.status_resultado in ('em_revisao', 'aprovado') and (
    old.valor_medido is distinct from new.valor_medido
    or old.valor_qualitativo is distinct from new.valor_qualitativo
    or old.amostra_id is distinct from new.amostra_id
    or old.parametro_id is distinct from new.parametro_id
    or old.contexto_legislacao_id is distinct from new.contexto_legislacao_id
    or old.datacoleta is distinct from new.datacoleta
    or old.metodo_analitico_id is distinct from new.metodo_analitico_id
    or old.snapshot_analitico is distinct from new.snapshot_analitico
    or old.versao is distinct from new.versao
    or old.limite_minimo_aplicado is distinct from new.limite_minimo_aplicado
    or old.limite_maximo_aplicado is distinct from new.limite_maximo_aplicado
    or old.tipo_limite_aplicado is distinct from new.tipo_limite_aplicado
    or old.criterio_legal_aplicado is distinct from new.criterio_legal_aplicado
    or old.fonte_legal_aplicada is distinct from new.fonte_legal_aplicada
  ) then
    raise exception 'Conteúdo analítico bloqueado durante revisão ou após aprovação';
  end if;
  return new;
end;
$$;

create or replace function public.enforce_resultado_workflow_event_signature()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  current_version integer;
  current_status text;
  current_signature_id bigint;
  required_action text;
  required_decision text;
  signature_record public.assinatura_eletronica%rowtype;
begin
  select result.versao, result.status_resultado,
         result.ultima_assinatura_eletronica_id
    into current_version, current_status, current_signature_id
  from public.resultado_analise result
  where result.id = new.resultado_id;

  if not found then
    raise exception 'Resultado do evento de workflow nao encontrado';
  end if;

  if current_status is distinct from new.status_novo then
    raise exception 'Evento de workflow nao corresponde ao estado atual do resultado';
  end if;

  if new.resultado_versao is not null and new.resultado_versao <> current_version then
    raise exception 'Versao do evento diverge da versao atual do resultado';
  end if;
  new.resultado_versao := current_version;

  required_action := case
    when new.status_anterior = 'em_revisao' and new.status_novo = 'aprovado'
      then 'APPROVE'
    when new.status_anterior = 'em_revisao' and new.status_novo = 'rejeitado'
      then 'REJECT'
    when new.status_anterior = 'aprovado' and new.status_novo = 'publicado'
      then 'PUBLISH'
    when new.status_anterior = 'aprovado' and new.status_novo = 'rascunho'
      then 'REOPEN'
    else null
  end;

  required_decision := case required_action
    when 'APPROVE' then 'aprovacao'
    when 'REJECT' then 'rejeicao'
    when 'PUBLISH' then 'publicacao'
    when 'REOPEN' then 'reabertura'
    else null
  end;

  if required_action is null then
    if new.assinatura_eletronica_id is not null then
      raise exception 'Assinatura nao permitida para este evento de workflow';
    end if;
    return new;
  end if;

  if new.decisao is distinct from required_decision then
    raise exception 'Decisao do evento nao corresponde a transicao assinada';
  end if;
  if new.actor_user_id is null then
    raise exception 'Ator e obrigatorio em evento de transicao assinada';
  end if;
  if new.assinatura_eletronica_id is null
     or new.assinatura_eletronica_id is distinct from current_signature_id then
    raise exception 'Evento nao referencia a ultima assinatura do resultado';
  end if;

  select signature.* into signature_record
  from public.assinatura_eletronica signature
  where signature.id = new.assinatura_eletronica_id;

  if not found
     or signature_record.entity_type is distinct from 'resultado_analise'
     or signature_record.entity_id is distinct from new.resultado_id::text
     or signature_record.signer_user_id is distinct from new.actor_user_id
     or signature_record.action is distinct from required_action
     or signature_record.entity_version is distinct from current_version
     or signature_record.status_origem is distinct from new.status_anterior
     or signature_record.status_destino is distinct from new.status_novo then
    raise exception 'Assinatura nao corresponde a entidade, ator, acao, versao e estados do evento';
  end if;

  if signature_record.authenticated_at > signature_record.signed_at
     or signature_record.signed_at > signature_record.authenticated_at + interval '5 minutes'
     or signature_record.signed_at < clock_timestamp() - interval '5 minutes'
     or signature_record.signed_at > clock_timestamp() + interval '30 seconds'
     or new.ocorrido_em < signature_record.signed_at - interval '30 seconds'
     or new.ocorrido_em > clock_timestamp() + interval '30 seconds' then
    raise exception 'Janela temporal da assinatura e do evento invalida';
  end if;

  if signature_record.request_id is distinct from new.request_id then
    raise exception 'Assinatura e evento devem pertencer a mesma requisicao';
  end if;

  if exists (
    select 1
    from public.resultado_workflow_evento used_event
    where used_event.assinatura_eletronica_id = new.assinatura_eletronica_id
  ) then
    raise exception 'Assinatura eletronica ja utilizada por outro evento';
  end if;

  if coalesce(new.metadata ->> 'versao', '') !~ '^[1-9][0-9]*$'
     or (new.metadata ->> 'versao')::integer <> current_version then
    raise exception 'Metadata do evento nao corresponde a versao assinada';
  end if;

  return new;
end;
$$;

create or replace function public.ensure_signed_result_transition_event()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  required_action text;
  matching_event_count integer;
begin
  required_action := case
    when old.status_resultado = 'em_revisao' and new.status_resultado = 'aprovado'
      then 'APPROVE'
    when old.status_resultado = 'em_revisao' and new.status_resultado = 'rejeitado'
      then 'REJECT'
    when old.status_resultado = 'aprovado' and new.status_resultado = 'publicado'
      then 'PUBLISH'
    when old.status_resultado = 'aprovado' and new.status_resultado = 'rascunho'
      then 'REOPEN'
    else null
  end;

  if required_action is null then
    return null;
  end if;

  select count(*)::integer into matching_event_count
  from public.resultado_workflow_evento event
  join public.assinatura_eletronica signature
    on signature.id = event.assinatura_eletronica_id
  where event.resultado_id = new.id
    and event.assinatura_eletronica_id = new.ultima_assinatura_eletronica_id
    and event.status_anterior = old.status_resultado
    and event.status_novo = new.status_resultado
    and event.resultado_versao = new.versao
    and signature.action = required_action;

  if matching_event_count <> 1 then
    raise exception 'Transicao assinada sem um unico evento correspondente';
  end if;

  return null;
end;
$$;

create or replace function public.enforce_amostra_conclusion_scope()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  expected_count integer;
  result_count integer;
  published_count integer;
begin
  if new.status_amostra = 'concluida'
     and old.status_amostra is distinct from new.status_amostra then
    select count(*)::integer
      into expected_count
    from public.amostra_parametro
    where amostra_id = new.id;

    select count(*)::integer,
           count(*) filter (where status_resultado = 'publicado')::integer
      into result_count, published_count
    from public.resultado_analise
    where amostra_id = new.id and deleted_at is null;

    if expected_count = 0
       or result_count <> expected_count
       or published_count <> expected_count then
      raise exception 'Amostra só pode ser concluída com um resultado publicado por parâmetro';
    end if;
  end if;
  return new;
end;
$$;

create or replace function public.enforce_laudo_emission_scope()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  sample_status text;
  expected_count integer;
  result_count integer;
  published_count integer;
begin
  select status_amostra into sample_status
  from public.amostra
  where id = new.amostra_id and deleted_at is null;

  if sample_status is distinct from 'concluida' then
    raise exception 'Laudo só pode ser emitido para amostra concluída';
  end if;

  select count(*)::integer into expected_count
  from public.amostra_parametro
  where amostra_id = new.amostra_id;

  select count(*)::integer,
         count(*) filter (where status_resultado = 'publicado')::integer
    into result_count, published_count
  from public.resultado_analise
  where amostra_id = new.amostra_id and deleted_at is null;

  if expected_count = 0
     or result_count <> expected_count
     or published_count <> expected_count then
    raise exception 'Escopo analítico incompleto para emissão do laudo';
  end if;

  if jsonb_typeof(new.snapshot -> 'resultados') is distinct from 'array'
     or jsonb_array_length(new.snapshot -> 'resultados') <> expected_count
     or new.snapshot #>> '{documento,id}' is distinct from new.id::text
     or new.snapshot #>> '{documento,numero}' is distinct from new.numero
     or new.snapshot #>> '{documento,versao}' is distinct from new.versao::text
     or new.snapshot #>> '{amostra,id}' is distinct from new.amostra_id::text then
    raise exception 'Snapshot do laudo não corresponde ao registro emitido';
  end if;

  if not exists (
    select 1
    from public.assinatura_eletronica signature
    where signature.id = new.assinatura_eletronica_id
      and signature.signer_user_id = new.emitido_por
      and signature.entity_type = 'laudo_analitico'
      and signature.entity_id = new.id::text
      and signature.action = 'REPORT_ISSUE'
      and signature.request_id is not distinct from new.request_id
      and coalesce(signature.metadata ->> 'entity_version', '') ~ '^[1-9][0-9]*$'
      and (signature.metadata ->> 'entity_version')::integer = new.versao
      and signature.authenticated_at <= signature.signed_at
      and signature.signed_at <= signature.authenticated_at + interval '5 minutes'
      and signature.signed_at >= clock_timestamp() - interval '5 minutes'
      and signature.signed_at <= clock_timestamp() + interval '30 seconds'
      and signature.signed_at >= new.emitido_em - interval '30 seconds'
      and signature.signed_at <= new.emitido_em + interval '30 seconds'
  ) then
    raise exception 'Assinatura eletrônica de emissão inválida';
  end if;
  return new;
end;
$$;

create or replace function public.protect_amostra_parametro_scope()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  target_sample_id integer;
begin
  target_sample_id := case when tg_op = 'INSERT' then new.amostra_id else old.amostra_id end;
  if exists (
    select 1 from public.resultado_analise where amostra_id = target_sample_id
  ) or (
    tg_op = 'UPDATE'
    and new.amostra_id is distinct from old.amostra_id
    and exists (
      select 1 from public.resultado_analise where amostra_id = new.amostra_id
    )
  ) then
    raise exception 'Escopo de parâmetros congelado após o primeiro resultado';
  end if;
  return case when tg_op = 'DELETE' then old else new end;
end;
$$;

drop trigger if exists prevent_referenced_method_update on public.metodo_analitico;
create trigger prevent_referenced_method_update
before update on public.metodo_analitico
for each row execute function public.prevent_referenced_method_content_update();

drop trigger if exists protect_resultado_workflow_content on public.resultado_analise;
create trigger protect_resultado_workflow_content
before update or delete on public.resultado_analise
for each row execute function public.protect_resultado_workflow_content();

drop trigger if exists bind_assinatura_context on public.assinatura_eletronica;
create trigger bind_assinatura_context
before insert on public.assinatura_eletronica
for each row execute function public.bind_assinatura_context();

drop trigger if exists enforce_resultado_workflow_event_signature
  on public.resultado_workflow_evento;
create trigger enforce_resultado_workflow_event_signature
before insert on public.resultado_workflow_evento
for each row execute function public.enforce_resultado_workflow_event_signature();

drop trigger if exists ensure_signed_result_transition_event
  on public.resultado_analise;
create constraint trigger ensure_signed_result_transition_event
after update of status_resultado on public.resultado_analise
deferrable initially deferred
for each row
when (old.status_resultado is distinct from new.status_resultado)
execute function public.ensure_signed_result_transition_event();

drop trigger if exists enforce_amostra_conclusion_scope on public.amostra;
create trigger enforce_amostra_conclusion_scope
before update of status_amostra on public.amostra
for each row execute function public.enforce_amostra_conclusion_scope();

drop trigger if exists enforce_laudo_emission_scope on public.laudo_analitico;
create trigger enforce_laudo_emission_scope
before insert on public.laudo_analitico
for each row execute function public.enforce_laudo_emission_scope();

drop trigger if exists protect_amostra_parametro_scope on public.amostra_parametro;
create trigger protect_amostra_parametro_scope
before insert or update or delete on public.amostra_parametro
for each row execute function public.protect_amostra_parametro_scope();

drop trigger if exists prevent_custodia_mutation on public.amostra_custodia_evento;
create trigger prevent_custodia_mutation before update or delete on public.amostra_custodia_evento
for each row execute function public.prevent_pilot_append_only_mutation();
drop trigger if exists prevent_assinatura_mutation on public.assinatura_eletronica;
create trigger prevent_assinatura_mutation before update or delete on public.assinatura_eletronica
for each row execute function public.prevent_pilot_append_only_mutation();
drop trigger if exists prevent_resultado_workflow_mutation on public.resultado_workflow_evento;
create trigger prevent_resultado_workflow_mutation before update or delete on public.resultado_workflow_evento
for each row execute function public.prevent_pilot_append_only_mutation();
drop trigger if exists prevent_resultado_snapshot_mutation on public.resultado_versao_snapshot;
create trigger prevent_resultado_snapshot_mutation before update or delete on public.resultado_versao_snapshot
for each row execute function public.prevent_pilot_append_only_mutation();
drop trigger if exists prevent_laudo_mutation on public.laudo_analitico;
create trigger prevent_laudo_mutation before update or delete on public.laudo_analitico
for each row execute function public.prevent_pilot_append_only_mutation();

alter table public.cliente enable row level security;
alter table public.pedido_analise enable row level security;
alter table public.metodo_analitico enable row level security;
alter table public.amostra_custodia_evento enable row level security;
alter table public.assinatura_eletronica enable row level security;
alter table public.resultado_versao_snapshot enable row level security;
alter table public.resultado_workflow_evento enable row level security;
alter table public.laudo_analitico enable row level security;

revoke all on table public.cliente from anon, authenticated;
revoke all on table public.pedido_analise from anon, authenticated;
revoke all on table public.metodo_analitico from anon, authenticated;
revoke all on table public.amostra_custodia_evento from anon, authenticated;
revoke all on table public.assinatura_eletronica from anon, authenticated;
revoke all on table public.resultado_versao_snapshot from anon, authenticated;
revoke all on table public.resultado_workflow_evento from anon, authenticated;
revoke all on table public.laudo_analitico from anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;
revoke execute on function public.prevent_pilot_append_only_mutation() from public, anon, authenticated;
revoke execute on function public.prevent_referenced_method_content_update() from public, anon, authenticated;
revoke execute on function public.bind_assinatura_context() from public, anon, authenticated;
revoke execute on function public.protect_resultado_workflow_content() from public, anon, authenticated;
revoke execute on function public.enforce_resultado_workflow_event_signature() from public, anon, authenticated;
revoke execute on function public.ensure_signed_result_transition_event() from public, anon, authenticated;
revoke execute on function public.enforce_amostra_conclusion_scope() from public, anon, authenticated;
revoke execute on function public.enforce_laudo_emission_scope() from public, anon, authenticated;
revoke execute on function public.protect_amostra_parametro_scope() from public, anon, authenticated;

comment on table public.amostra_custodia_evento is
  'Cadeia de custódia append-only de recebimentos, movimentações e mudanças de estado.';
comment on table public.assinatura_eletronica is
  'Evidências de assinatura por reautenticação; nunca contém senha ou token.';
comment on table public.resultado_workflow_evento is
  'Histórico append-only do ciclo de revisão e publicação de resultados.';
comment on table public.resultado_versao_snapshot is
  'Versoes append-only do contexto analitico completo de cada resultado.';
comment on table public.laudo_analitico is
  'Versões imutáveis de laudos, cada uma com snapshot e hash do conteúdo.';

commit;
