begin;

-- Inventário de insumos, reagentes, padrões e consumíveis.
create table if not exists public.insumo (
  id bigint generated by default as identity primary key,
  codigo text not null,
  nome text not null,
  tipo text not null default 'REAGENTE'
    check (tipo in ('REAGENTE', 'PADRAO', 'CONSUMIVEL', 'OUTRO')),
  unidade_medida text not null,
  estoque_minimo numeric(18, 6) not null default 0 check (estoque_minimo >= 0),
  fabricante text,
  condicao_armazenamento text,
  ativo boolean not null default true,
  deleted_at timestamptz,
  deleted_by uuid references public.usuario(id) on update cascade on delete set null,
  deletion_reason text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  check (length(trim(codigo)) between 1 and 80),
  check (length(trim(nome)) between 1 and 200),
  check (length(trim(unidade_medida)) between 1 and 30)
);

create unique index if not exists insumo_codigo_active_uidx
  on public.insumo (lower(codigo)) where deleted_at is null;
create index if not exists insumo_nome_idx on public.insumo (lower(nome));
create index if not exists insumo_active_idx
  on public.insumo (ativo, created_at desc) where deleted_at is null;

create table if not exists public.insumo_lote (
  id bigint generated by default as identity primary key,
  insumo_id bigint not null references public.insumo(id) on update cascade on delete restrict,
  numero_lote text not null,
  validade date,
  data_recebimento date not null default current_date,
  quantidade_inicial numeric(18, 6) not null default 0 check (quantidade_inicial >= 0),
  quantidade_atual numeric(18, 6) not null default 0 check (quantidade_atual >= 0),
  fornecedor text,
  local_armazenamento text,
  certificado_url text,
  status text not null default 'DISPONIVEL'
    check (status in ('DISPONIVEL', 'QUARENTENA', 'BLOQUEADO', 'ESGOTADO')),
  deleted_at timestamptz,
  deleted_by uuid references public.usuario(id) on update cascade on delete set null,
  deletion_reason text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  check (length(trim(numero_lote)) between 1 and 120)
);

create unique index if not exists insumo_lote_active_uidx
  on public.insumo_lote (insumo_id, lower(numero_lote)) where deleted_at is null;
create index if not exists insumo_lote_validade_idx
  on public.insumo_lote (validade) where deleted_at is null and quantidade_atual > 0;
create index if not exists insumo_lote_status_idx
  on public.insumo_lote (status, insumo_id) where deleted_at is null;

create table if not exists public.estoque_movimentacao (
  id bigint generated by default as identity primary key,
  insumo_lote_id bigint not null references public.insumo_lote(id) on update cascade on delete restrict,
  tipo text not null
    check (tipo in ('ENTRADA', 'SAIDA', 'AJUSTE_POSITIVO', 'AJUSTE_NEGATIVO')),
  quantidade numeric(18, 6) not null check (quantidade > 0),
  saldo_anterior numeric(18, 6) not null check (saldo_anterior >= 0),
  saldo_posterior numeric(18, 6) not null check (saldo_posterior >= 0),
  motivo text not null check (length(trim(motivo)) between 3 and 500),
  referencia text,
  realizado_por uuid not null references public.usuario(id) on update cascade on delete restrict,
  created_at timestamptz not null default timezone('utc', now()),
  check (
    (tipo in ('ENTRADA', 'AJUSTE_POSITIVO') and saldo_posterior = saldo_anterior + quantidade)
    or
    (tipo in ('SAIDA', 'AJUSTE_NEGATIVO') and saldo_posterior = saldo_anterior - quantidade)
  )
);

create index if not exists estoque_movimentacao_lote_idx
  on public.estoque_movimentacao (insumo_lote_id, created_at desc);
create index if not exists estoque_movimentacao_usuario_idx
  on public.estoque_movimentacao (realizado_por, created_at desc);

create or replace function public.prevent_stock_movement_mutation()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  raise exception 'Movimentações de estoque são imutáveis; registre um ajuste compensatório';
end;
$$;

drop trigger if exists prevent_stock_movement_update on public.estoque_movimentacao;
create trigger prevent_stock_movement_update
before update or delete on public.estoque_movimentacao
for each row execute function public.prevent_stock_movement_mutation();

-- Cadastro, disponibilidade, calibração e manutenção de equipamentos.
create table if not exists public.equipamento (
  id bigint generated by default as identity primary key,
  codigo text not null,
  nome text not null,
  fabricante text,
  modelo text,
  numero_serie text,
  localizacao text,
  criticidade text not null default 'MEDIA'
    check (criticidade in ('BAIXA', 'MEDIA', 'ALTA')),
  status text not null default 'ATIVO'
    check (status in ('ATIVO', 'MANUTENCAO', 'FORA_DE_USO')),
  requer_calibracao boolean not null default true,
  frequencia_calibracao_dias integer check (frequencia_calibracao_dias is null or frequencia_calibracao_dias > 0),
  ultima_calibracao date,
  proxima_calibracao date,
  deleted_at timestamptz,
  deleted_by uuid references public.usuario(id) on update cascade on delete set null,
  deletion_reason text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  check (length(trim(codigo)) between 1 and 80),
  check (length(trim(nome)) between 1 and 200),
  check (ultima_calibracao is null or proxima_calibracao is null or ultima_calibracao <= proxima_calibracao)
);

create unique index if not exists equipamento_codigo_active_uidx
  on public.equipamento (lower(codigo)) where deleted_at is null;
create index if not exists equipamento_calibracao_idx
  on public.equipamento (proxima_calibracao) where deleted_at is null and requer_calibracao;
create index if not exists equipamento_status_idx
  on public.equipamento (status, created_at desc) where deleted_at is null;

create table if not exists public.equipamento_evento (
  id bigint generated by default as identity primary key,
  equipamento_id bigint not null references public.equipamento(id) on update cascade on delete restrict,
  tipo text not null
    check (tipo in ('CALIBRACAO', 'MANUTENCAO_PREVENTIVA', 'MANUTENCAO_CORRETIVA')),
  status text not null default 'AGENDADO'
    check (status in ('AGENDADO', 'EM_ANDAMENTO', 'CONCLUIDO', 'CANCELADO')),
  descricao text not null check (length(trim(descricao)) between 3 and 1000),
  fornecedor text,
  agendado_para timestamptz,
  iniciado_em timestamptz,
  concluido_em timestamptz,
  resultado text check (resultado is null or resultado in ('APROVADO', 'REPROVADO', 'NAO_APLICAVEL')),
  certificado_url text,
  observacao text,
  proxima_calibracao date,
  criado_por uuid not null references public.usuario(id) on update cascade on delete restrict,
  concluido_por uuid references public.usuario(id) on update cascade on delete restrict,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  check (concluido_em is null or iniciado_em is null or concluido_em >= iniciado_em)
);

create index if not exists equipamento_evento_historico_idx
  on public.equipamento_evento (equipamento_id, created_at desc);
create index if not exists equipamento_evento_aberto_idx
  on public.equipamento_evento (equipamento_id, status)
  where status in ('AGENDADO', 'EM_ANDAMENTO');

create table if not exists public.equipamento_utilizacao (
  id bigint generated by default as identity primary key,
  equipamento_id bigint not null references public.equipamento(id) on update cascade on delete restrict,
  amostra_id integer references public.amostra(id) on update cascade on delete restrict,
  resultado_analise_id integer references public.resultado_analise(id) on update cascade on delete restrict,
  finalidade text not null check (length(trim(finalidade)) between 3 and 500),
  utilizado_por uuid not null references public.usuario(id) on update cascade on delete restrict,
  utilizado_em timestamptz not null default timezone('utc', now()),
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists equipamento_utilizacao_equipamento_idx
  on public.equipamento_utilizacao (equipamento_id, utilizado_em desc);
create index if not exists equipamento_utilizacao_amostra_idx
  on public.equipamento_utilizacao (amostra_id) where amostra_id is not null;
create index if not exists equipamento_utilizacao_resultado_idx
  on public.equipamento_utilizacao (resultado_analise_id) where resultado_analise_id is not null;

create or replace function public.prevent_final_equipment_event_mutation()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if tg_op = 'DELETE' or old.status in ('CONCLUIDO', 'CANCELADO') then
    raise exception 'Eventos concluídos ou cancelados são imutáveis';
  end if;
  return new;
end;
$$;

drop trigger if exists prevent_final_equipment_event_update on public.equipamento_evento;
create trigger prevent_final_equipment_event_update
before update or delete on public.equipamento_evento
for each row execute function public.prevent_final_equipment_event_mutation();

create or replace function public.prevent_equipment_usage_mutation()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  raise exception 'Registros de utilização de equipamentos são imutáveis';
end;
$$;

drop trigger if exists prevent_equipment_usage_update on public.equipamento_utilizacao;
create trigger prevent_equipment_usage_update
before update or delete on public.equipamento_utilizacao
for each row execute function public.prevent_equipment_usage_mutation();

-- Sistema de gestão da qualidade: não conformidades, desvios e ações CAPA.
create sequence if not exists public.qms_ocorrencia_codigo_seq;

create table if not exists public.qms_ocorrencia (
  id bigint generated by default as identity primary key,
  codigo text not null unique,
  tipo text not null check (tipo in ('NAO_CONFORMIDADE', 'DESVIO')),
  titulo text not null check (length(trim(titulo)) between 3 and 200),
  descricao text not null check (length(trim(descricao)) between 10 and 5000),
  origem text,
  gravidade text not null default 'MEDIA'
    check (gravidade in ('BAIXA', 'MEDIA', 'ALTA', 'CRITICA')),
  status text not null default 'ABERTA'
    check (status in ('ABERTA', 'EM_INVESTIGACAO', 'PLANO_ACAO', 'VERIFICACAO', 'ENCERRADA', 'CANCELADA')),
  responsavel_id uuid references public.usuario(id) on update cascade on delete set null,
  aberta_por uuid not null references public.usuario(id) on update cascade on delete restrict,
  prazo date,
  contencao text,
  causa_raiz text,
  verificacao_eficacia text,
  decisao_final text,
  encerrada_em timestamptz,
  encerrada_por uuid references public.usuario(id) on update cascade on delete set null,
  deleted_at timestamptz,
  deleted_by uuid references public.usuario(id) on update cascade on delete set null,
  deletion_reason text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists qms_ocorrencia_status_idx
  on public.qms_ocorrencia (status, prazo, created_at desc) where deleted_at is null;
create index if not exists qms_ocorrencia_responsavel_idx
  on public.qms_ocorrencia (responsavel_id, created_at desc) where deleted_at is null;

create table if not exists public.qms_acao_capa (
  id bigint generated by default as identity primary key,
  ocorrencia_id bigint not null references public.qms_ocorrencia(id) on update cascade on delete restrict,
  tipo text not null check (tipo in ('CORRETIVA', 'PREVENTIVA')),
  descricao text not null check (length(trim(descricao)) between 5 and 2000),
  responsavel_id uuid references public.usuario(id) on update cascade on delete set null,
  prazo date,
  status text not null default 'PENDENTE'
    check (status in ('PENDENTE', 'EM_ANDAMENTO', 'CONCLUIDA', 'CANCELADA')),
  evidencia text,
  concluida_em timestamptz,
  criado_por uuid not null references public.usuario(id) on update cascade on delete restrict,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists qms_acao_ocorrencia_idx
  on public.qms_acao_capa (ocorrencia_id, status, prazo);
create index if not exists qms_acao_responsavel_idx
  on public.qms_acao_capa (responsavel_id, status, prazo);

drop trigger if exists set_insumo_updated_at on public.insumo;
create trigger set_insumo_updated_at before update on public.insumo
for each row execute function public.set_updated_at();

drop trigger if exists set_insumo_lote_updated_at on public.insumo_lote;
create trigger set_insumo_lote_updated_at before update on public.insumo_lote
for each row execute function public.set_updated_at();

drop trigger if exists set_equipamento_updated_at on public.equipamento;
create trigger set_equipamento_updated_at before update on public.equipamento
for each row execute function public.set_updated_at();

drop trigger if exists set_equipamento_evento_updated_at on public.equipamento_evento;
create trigger set_equipamento_evento_updated_at before update on public.equipamento_evento
for each row execute function public.set_updated_at();

drop trigger if exists set_qms_ocorrencia_updated_at on public.qms_ocorrencia;
create trigger set_qms_ocorrencia_updated_at before update on public.qms_ocorrencia
for each row execute function public.set_updated_at();

drop trigger if exists set_qms_acao_capa_updated_at on public.qms_acao_capa;
create trigger set_qms_acao_capa_updated_at before update on public.qms_acao_capa
for each row execute function public.set_updated_at();

alter table public.insumo enable row level security;
alter table public.insumo_lote enable row level security;
alter table public.estoque_movimentacao enable row level security;
alter table public.equipamento enable row level security;
alter table public.equipamento_evento enable row level security;
alter table public.equipamento_utilizacao enable row level security;
alter table public.qms_ocorrencia enable row level security;
alter table public.qms_acao_capa enable row level security;

revoke all on table public.insumo from anon, authenticated;
revoke all on table public.insumo_lote from anon, authenticated;
revoke all on table public.estoque_movimentacao from anon, authenticated;
revoke all on table public.equipamento from anon, authenticated;
revoke all on table public.equipamento_evento from anon, authenticated;
revoke all on table public.equipamento_utilizacao from anon, authenticated;
revoke all on table public.qms_ocorrencia from anon, authenticated;
revoke all on table public.qms_acao_capa from anon, authenticated;
revoke all on sequence public.insumo_id_seq from anon, authenticated;
revoke all on sequence public.insumo_lote_id_seq from anon, authenticated;
revoke all on sequence public.estoque_movimentacao_id_seq from anon, authenticated;
revoke all on sequence public.equipamento_id_seq from anon, authenticated;
revoke all on sequence public.equipamento_evento_id_seq from anon, authenticated;
revoke all on sequence public.equipamento_utilizacao_id_seq from anon, authenticated;
revoke all on sequence public.qms_ocorrencia_id_seq from anon, authenticated;
revoke all on sequence public.qms_ocorrencia_codigo_seq from anon, authenticated;
revoke all on sequence public.qms_acao_capa_id_seq from anon, authenticated;
revoke execute on function public.prevent_stock_movement_mutation() from public, anon, authenticated;
revoke execute on function public.prevent_final_equipment_event_mutation() from public, anon, authenticated;
revoke execute on function public.prevent_equipment_usage_mutation() from public, anon, authenticated;

comment on table public.estoque_movimentacao is
  'Razão imutável de estoque. Correções devem ser lançadas como ajustes compensatórios.';
comment on column public.equipamento.proxima_calibracao is
  'Equipamentos que exigem calibração ficam bloqueados quando esta data está ausente ou vencida.';
comment on table public.equipamento_utilizacao is
  'Histórico imutável de uso; a API só registra utilização quando o equipamento está operacionalmente disponível.';
comment on table public.qms_ocorrencia is
  'Registro controlado de não conformidades e desvios, com decisões e CAPA auditadas.';

commit;
