begin;

create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  occurred_at timestamptz not null default timezone('utc', now()),
  actor_user_id uuid references public.usuario(id) on update cascade on delete set null,
  action text not null check (action in ('CREATE', 'UPDATE', 'ARCHIVE', 'RESTORE', 'IMPORT', 'ROLE_CHANGE')),
  entity_type text not null,
  entity_id text,
  before_data jsonb,
  after_data jsonb,
  metadata jsonb not null default '{}'::jsonb,
  request_id uuid
);

create index if not exists audit_log_entity_idx
  on public.audit_log (entity_type, entity_id, occurred_at desc);
create index if not exists audit_log_actor_idx
  on public.audit_log (actor_user_id, occurred_at desc);
create index if not exists audit_log_occurred_at_idx
  on public.audit_log (occurred_at desc);

create or replace function public.prevent_audit_log_mutation()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  raise exception 'Registros de auditoria são imutáveis';
end;
$$;

drop trigger if exists prevent_audit_log_update on public.audit_log;
create trigger prevent_audit_log_update
before update or delete on public.audit_log
for each row execute function public.prevent_audit_log_mutation();

alter table public.amostra
  add column if not exists deleted_at timestamptz,
  add column if not exists deleted_by uuid references public.usuario(id) on update cascade on delete set null,
  add column if not exists deletion_reason text;

alter table public.resultado_analise
  add column if not exists deleted_at timestamptz,
  add column if not exists deleted_by uuid references public.usuario(id) on update cascade on delete set null,
  add column if not exists deletion_reason text;

create index if not exists amostra_active_created_idx
  on public.amostra (created_at desc) where deleted_at is null;
create index if not exists resultado_active_data_idx
  on public.resultado_analise (datacoleta desc) where deleted_at is null;

alter table public.audit_log enable row level security;
revoke all on table public.audit_log from anon, authenticated;
revoke all on sequence public.audit_log_id_seq from anon, authenticated;
revoke execute on function public.prevent_audit_log_mutation() from public, anon, authenticated;

comment on table public.audit_log is
  'Trilha de auditoria imutável de alterações realizadas pela API.';
comment on column public.amostra.deleted_at is
  'Arquivamento lógico; amostras e seus vínculos não são removidos fisicamente.';
comment on column public.resultado_analise.deleted_at is
  'Arquivamento lógico; resultados laboratoriais não são removidos fisicamente.';

commit;
