begin;

-- Catálogo legal versionado. Os limites são vinculados ao contexto de aplicação
-- da norma (classe da água, tipo de lançamento etc.), não apenas à legislação.
alter table public.legislacao
  add column if not exists orgao_emissor text,
  add column if not exists fonte_url text,
  add column if not exists observacao text;

update public.legislacao
set orgao_emissor = 'Ministério da Saúde',
    fonte_url = 'https://bvsms.saude.gov.br/bvs/saudelegis/gm/2021/prt0888_24_05_2021_rep.html',
    observacao = 'Anexo XX da Portaria de Consolidação GM/MS nº 5/2017, alterado pelas Portarias GM/MS nº 888/2021 e nº 2.472/2021.'
where lower(sigla) = lower('Portaria 888/2021');

update public.legislacao
set orgao_emissor = 'Conselho Nacional do Meio Ambiente (CONAMA)',
    fonte_url = 'https://www.ana.gov.br/portalpnqa/Publicacao/RESOLUCAO_CONAMA_n_357.pdf',
    observacao = 'Classificação dos corpos de água e padrões de qualidade por classe e salinidade.'
where lower(sigla) = lower('CONAMA nº 357/2005');

update public.legislacao
set orgao_emissor = 'Conselho Nacional do Meio Ambiente (CONAMA)',
    fonte_url = 'https://conama.mma.gov.br/?id=627&option=com_sisconama&task=arquivo.download',
    observacao = 'Condições e padrões de lançamento de efluentes; exigências locais e do licenciamento podem ser mais restritivas.'
where lower(sigla) = lower('CONAMA nº 430/2011');

create table if not exists public.legislacao_contexto (
  id integer generated by default as identity primary key,
  legislacao_id integer not null references public.legislacao(id) on update cascade on delete cascade,
  matriz_id integer not null references public.matriz(id) on update cascade on delete restrict,
  codigo text not null unique,
  nome text not null,
  descricao text,
  referencia_legal text not null,
  ordem integer not null default 0,
  ativo boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists legislacao_contexto_nome_uidx
  on public.legislacao_contexto (legislacao_id, matriz_id, lower(nome));
create index if not exists legislacao_contexto_filtro_idx
  on public.legislacao_contexto (matriz_id, legislacao_id, ativo, ordem);

drop trigger if exists set_legislacao_contexto_updated_at on public.legislacao_contexto;
create trigger set_legislacao_contexto_updated_at
before update on public.legislacao_contexto
for each row execute function public.set_updated_at();

insert into public.legislacao_contexto
  (legislacao_id, matriz_id, codigo, nome, descricao, referencia_legal, ordem)
select l.id, m.id, v.codigo, v.nome, v.descricao, v.referencia, v.ordem
from (values
  ('Portaria 888/2021', 'Água', 'P888_POTABILIDADE', 'Água para consumo humano — padrão de potabilidade', 'Padrões microbiológicos, substâncias químicas, cianotoxinas e padrão organoléptico.', 'Anexo XX; arts. 27 a 42; Anexos 1, 9, 10 e 11', 10),
  ('CONAMA nº 357/2005', 'Água Bruta', 'C357_DOCE_1', 'Água doce — Classe 1', 'Águas doces enquadradas na classe 1.', 'Arts. 14 e 15; Tabela I', 20),
  ('CONAMA nº 357/2005', 'Água Bruta', 'C357_DOCE_1_AQUICULTURA', 'Água doce — Classe 1 (pesca/cultivo para consumo intensivo)', 'Aplicam-se os padrões da classe 1 e as substituições adicionais para pesca ou cultivo destinado ao consumo intensivo.', 'Art. 14, III; Tabela II', 21),
  ('CONAMA nº 357/2005', 'Água Bruta', 'C357_DOCE_2', 'Água doce — Classe 2', 'Padrões da classe 1, exceto as condições e os limites específicos da classe 2.', 'Art. 15', 22),
  ('CONAMA nº 357/2005', 'Água Bruta', 'C357_DOCE_3', 'Água doce — Classe 3', 'Águas doces enquadradas na classe 3.', 'Art. 16; Tabela III', 23),
  ('CONAMA nº 357/2005', 'Água Bruta', 'C357_DOCE_4', 'Água doce — Classe 4', 'Águas doces enquadradas na classe 4.', 'Art. 17', 24),
  ('CONAMA nº 357/2005', 'Água Bruta', 'C357_SALINA_1', 'Água salina — Classe 1', 'Águas salinas enquadradas na classe 1.', 'Art. 18; Tabela IV', 30),
  ('CONAMA nº 357/2005', 'Água Bruta', 'C357_SALINA_1_AQUICULTURA', 'Água salina — Classe 1 (pesca/cultivo para consumo intensivo)', 'Padrões da classe 1 com substituições adicionais para pesca ou cultivo destinado ao consumo intensivo.', 'Art. 18, III; Tabela V', 31),
  ('CONAMA nº 357/2005', 'Água Bruta', 'C357_SALINA_2', 'Água salina — Classe 2', 'Padrões da classe 1, exceto as condições e os limites específicos da classe 2.', 'Art. 19; Tabela VI', 32),
  ('CONAMA nº 357/2005', 'Água Bruta', 'C357_SALINA_3', 'Água salina — Classe 3', 'Águas salinas enquadradas na classe 3.', 'Art. 20', 33),
  ('CONAMA nº 357/2005', 'Água Bruta', 'C357_SALOBRA_1', 'Água salobra — Classe 1', 'Águas salobras enquadradas na classe 1.', 'Art. 21; Tabela VII', 40),
  ('CONAMA nº 357/2005', 'Água Bruta', 'C357_SALOBRA_1_AQUICULTURA', 'Água salobra — Classe 1 (pesca/cultivo para consumo intensivo)', 'Padrões da classe 1 com substituições adicionais para pesca ou cultivo destinado ao consumo intensivo.', 'Art. 21, III; Tabela VIII', 41),
  ('CONAMA nº 357/2005', 'Água Bruta', 'C357_SALOBRA_2', 'Água salobra — Classe 2', 'Padrões da classe 1, exceto as condições e os limites específicos da classe 2.', 'Art. 22; Tabela IX', 42),
  ('CONAMA nº 357/2005', 'Água Bruta', 'C357_SALOBRA_3', 'Água salobra — Classe 3', 'Águas salobras enquadradas na classe 3.', 'Art. 23', 43),
  ('CONAMA nº 430/2011', 'Efluente', 'C430_GERAL', 'Efluentes — lançamento geral', 'Condições e padrões gerais para lançamento direto de efluentes.', 'Art. 16; Tabela I', 50),
  ('CONAMA nº 430/2011', 'Efluente', 'C430_ESGOTO_SANITARIO', 'Esgotos sanitários — lançamento direto', 'Condições e padrões específicos para lançamento direto de efluentes oriundos de sistemas de tratamento de esgotos sanitários.', 'Arts. 21 e 21-A', 51),
  ('CONAMA nº 430/2011', 'Efluente', 'C430_EMISSARIO_SUBMARINO', 'Esgotos sanitários — emissário submarino', 'Condições aplicáveis ao lançamento de efluentes de sistemas de tratamento de esgotos sanitários por meio de emissários submarinos.', 'Art. 22', 52)
) as v(sigla, matriz, codigo, nome, descricao, referencia, ordem)
join public.legislacao l on lower(l.sigla) = lower(v.sigla)
join public.matriz m on lower(m.nome) = lower(v.matriz)
on conflict (codigo) do update
set nome = excluded.nome,
    descricao = excluded.descricao,
    referencia_legal = excluded.referencia_legal,
    ordem = excluded.ordem,
    ativo = true;

alter table public.parametro
  add column if not exists contexto_legislacao_id integer references public.legislacao_contexto(id) on update cascade on delete restrict,
  add column if not exists categoria text not null default 'Outros',
  add column if not exists tipo_resultado text not null default 'numerico',
  add column if not exists tipo_limite text not null default 'maximo',
  add column if not exists criterio_texto text,
  add column if not exists fonte_referencia text,
  add column if not exists ordem integer not null default 0,
  add column if not exists ativo boolean not null default true;

alter table public.parametro drop constraint if exists parametro_tipo_resultado_check;
alter table public.parametro add constraint parametro_tipo_resultado_check
  check (tipo_resultado in ('numerico', 'qualitativo'));
alter table public.parametro drop constraint if exists parametro_tipo_limite_check;
alter table public.parametro add constraint parametro_tipo_limite_check
  check (tipo_limite in ('maximo', 'minimo', 'faixa', 'ausencia', 'informativo'));

drop index if exists public.parametro_contexto_uidx;
create unique index if not exists parametro_contexto_legal_uidx
  on public.parametro (lower(nome), contexto_legislacao_id)
  where contexto_legislacao_id is not null;
create index if not exists parametro_contexto_legal_idx
  on public.parametro (contexto_legislacao_id, ativo, categoria, ordem, nome);

alter table public.resultado_analise
  alter column valor_medido drop not null,
  add column if not exists valor_qualitativo text,
  add column if not exists contexto_legislacao_id integer references public.legislacao_contexto(id) on update cascade on delete restrict,
  add column if not exists limite_minimo_aplicado numeric(18, 6),
  add column if not exists limite_maximo_aplicado numeric(18, 6),
  add column if not exists tipo_limite_aplicado text,
  add column if not exists criterio_legal_aplicado text,
  add column if not exists fonte_legal_aplicada text;

alter table public.resultado_analise drop constraint if exists resultado_analise_valor_medido_check;
alter table public.resultado_analise drop constraint if exists resultado_valor_preenchido_check;
alter table public.resultado_analise add constraint resultado_valor_preenchido_check
  check (
    (valor_medido is not null and valor_medido >= 0 and valor_qualitativo is null)
    or (valor_medido is null and nullif(trim(valor_qualitativo), '') is not null)
  );

create index if not exists resultado_contexto_idx
  on public.resultado_analise (contexto_legislacao_id, datacoleta desc);

-- Funções temporárias tornam o catálogo legível e permitem repetir a migration
-- com segurança sem deixar funções auxiliares no schema público.
create or replace function pg_temp.add_legal_params(p_contexto text, p_dados jsonb)
returns void
language sql
as $$
  insert into public.parametro (
    nome, unidade_medida, valor_parametro, limite_minimo, limite_maximo,
    matriz_id, legislacao_id, contexto_legislacao_id, categoria,
    tipo_resultado, tipo_limite, criterio_texto, fonte_referencia, ordem, ativo
  )
  select
    d.nome,
    coalesce(d.unidade, ''),
    null,
    d.minimo,
    d.maximo,
    c.matriz_id,
    c.legislacao_id,
    c.id,
    coalesce(d.categoria, 'Outros'),
    coalesce(d.tipo_resultado, 'numerico'),
    coalesce(d.tipo_limite,
      case when d.minimo is not null and d.maximo is not null then 'faixa'
           when d.minimo is not null then 'minimo'
           when d.maximo is not null then 'maximo'
           else 'informativo' end),
    d.criterio,
    coalesce(d.referencia, c.referencia_legal),
    coalesce(d.ordem, 0),
    true
  from public.legislacao_contexto c
  cross join jsonb_to_recordset(p_dados) as d(
    nome text, unidade text, minimo numeric, maximo numeric, categoria text,
    tipo_resultado text, tipo_limite text, criterio text, referencia text, ordem integer
  )
  where c.codigo = p_contexto
  on conflict (lower(nome), contexto_legislacao_id)
    where contexto_legislacao_id is not null
  do update set
    unidade_medida = excluded.unidade_medida,
    limite_minimo = excluded.limite_minimo,
    limite_maximo = excluded.limite_maximo,
    matriz_id = excluded.matriz_id,
    legislacao_id = excluded.legislacao_id,
    categoria = excluded.categoria,
    tipo_resultado = excluded.tipo_resultado,
    tipo_limite = excluded.tipo_limite,
    criterio_texto = excluded.criterio_texto,
    fonte_referencia = excluded.fonte_referencia,
    ordem = excluded.ordem,
    ativo = true;
$$;

create or replace function pg_temp.clone_legal_params(p_origem text, p_destino text)
returns void
language sql
as $$
  insert into public.parametro (
    nome, unidade_medida, valor_parametro, limite_minimo, limite_maximo,
    matriz_id, legislacao_id, contexto_legislacao_id, categoria,
    tipo_resultado, tipo_limite, criterio_texto, fonte_referencia, ordem, ativo
  )
  select
    p.nome, p.unidade_medida, null, p.limite_minimo, p.limite_maximo,
    destino.matriz_id, destino.legislacao_id, destino.id, p.categoria,
    p.tipo_resultado, p.tipo_limite, p.criterio_texto,
    destino.referencia_legal, p.ordem, true
  from public.parametro p
  join public.legislacao_contexto origem on origem.id = p.contexto_legislacao_id
  cross join public.legislacao_contexto destino
  where origem.codigo = p_origem and destino.codigo = p_destino
  on conflict (lower(nome), contexto_legislacao_id)
    where contexto_legislacao_id is not null
  do nothing;
$$;

-- Portaria GM/MS nº 888/2021 (com a alteração da Portaria nº 2.472/2021).
select pg_temp.add_legal_params('P888_POTABILIDADE', $json$
[
  {"nome":"Escherichia coli","unidade":"Presença/ausência em 100 mL","categoria":"Microbiológicos","tipo_resultado":"qualitativo","tipo_limite":"ausencia","criterio":"Ausência em 100 mL","referencia":"Anexo 1"},
  {"nome":"Coliformes totais — saída do tratamento","unidade":"Presença/ausência em 100 mL","categoria":"Microbiológicos","tipo_resultado":"qualitativo","tipo_limite":"ausencia","criterio":"Ausência em 100 mL na saída do tratamento","referencia":"Anexo 1"},
  {"nome":"Antimônio","unidade":"mg/L","maximo":0.006,"categoria":"Inorgânicos","referencia":"Anexo 9"},
  {"nome":"Arsênio","unidade":"mg/L","maximo":0.01,"categoria":"Inorgânicos","referencia":"Anexo 9"},
  {"nome":"Bário","unidade":"mg/L","maximo":0.7,"categoria":"Inorgânicos","referencia":"Anexo 9"},
  {"nome":"Cádmio","unidade":"mg/L","maximo":0.003,"categoria":"Inorgânicos","referencia":"Anexo 9"},
  {"nome":"Chumbo","unidade":"mg/L","maximo":0.01,"categoria":"Inorgânicos","referencia":"Anexo 9"},
  {"nome":"Cobre","unidade":"mg/L","maximo":2,"categoria":"Inorgânicos","referencia":"Anexo 9"},
  {"nome":"Cromo","unidade":"mg/L","maximo":0.05,"categoria":"Inorgânicos","referencia":"Anexo 9"},
  {"nome":"Fluoreto","unidade":"mg/L","maximo":1.5,"categoria":"Inorgânicos","referencia":"Anexo 9"},
  {"nome":"Mercúrio total","unidade":"mg/L","maximo":0.001,"categoria":"Inorgânicos","referencia":"Anexo 9"},
  {"nome":"Níquel","unidade":"mg/L","maximo":0.07,"categoria":"Inorgânicos","referencia":"Anexo 9"},
  {"nome":"Nitrato (como N)","unidade":"mg/L","maximo":10,"categoria":"Inorgânicos","referencia":"Anexo 9"},
  {"nome":"Nitrito (como N)","unidade":"mg/L","maximo":1,"categoria":"Inorgânicos","referencia":"Anexo 9"},
  {"nome":"Selênio","unidade":"mg/L","maximo":0.04,"categoria":"Inorgânicos","referencia":"Anexo 9"},
  {"nome":"Urânio","unidade":"mg/L","maximo":0.03,"categoria":"Inorgânicos","referencia":"Anexo 9"},
  {"nome":"1,2-Dicloroetano","unidade":"µg/L","maximo":5,"categoria":"Orgânicos","referencia":"Anexo 9"},
  {"nome":"Acrilamida","unidade":"µg/L","maximo":0.5,"categoria":"Orgânicos","referencia":"Anexo 9"},
  {"nome":"Benzeno","unidade":"µg/L","maximo":5,"categoria":"Orgânicos","referencia":"Anexo 9"},
  {"nome":"Benzo[a]pireno","unidade":"µg/L","maximo":0.4,"categoria":"Orgânicos","referencia":"Anexo 9"},
  {"nome":"Cloreto de vinila","unidade":"µg/L","maximo":0.5,"categoria":"Orgânicos","referencia":"Anexo 9"},
  {"nome":"Di(2-etilhexil) ftalato","unidade":"µg/L","maximo":8,"categoria":"Orgânicos","referencia":"Anexo 9"},
  {"nome":"Diclorometano","unidade":"µg/L","maximo":20,"categoria":"Orgânicos","referencia":"Anexo 9"},
  {"nome":"1,4-Dioxano","unidade":"µg/L","maximo":48,"categoria":"Orgânicos","referencia":"Anexo 9"},
  {"nome":"Epicloridrina","unidade":"µg/L","maximo":0.4,"categoria":"Orgânicos","referencia":"Anexo 9"},
  {"nome":"Etilbenzeno","unidade":"µg/L","maximo":300,"categoria":"Orgânicos","referencia":"Anexo 9"},
  {"nome":"Pentaclorofenol","unidade":"µg/L","maximo":9,"categoria":"Orgânicos","referencia":"Anexo 9"},
  {"nome":"Tetracloreto de carbono","unidade":"µg/L","maximo":4,"categoria":"Orgânicos","referencia":"Anexo 9"},
  {"nome":"Tetracloroeteno","unidade":"µg/L","maximo":40,"categoria":"Orgânicos","referencia":"Anexo 9"},
  {"nome":"Tolueno","unidade":"µg/L","maximo":30,"categoria":"Orgânicos","referencia":"Anexo 9"},
  {"nome":"Tricloroeteno","unidade":"µg/L","maximo":4,"categoria":"Orgânicos","referencia":"Anexo 9"},
  {"nome":"Xilenos","unidade":"µg/L","maximo":500,"categoria":"Orgânicos","referencia":"Anexo 9"},
  {"nome":"2,4-D","unidade":"µg/L","maximo":30,"categoria":"Agrotóxicos e metabólitos","referencia":"Anexo 9"},
  {"nome":"Alacloro","unidade":"µg/L","maximo":20,"categoria":"Agrotóxicos e metabólitos","referencia":"Anexo 9"},
  {"nome":"Aldicarbe + Aldicarbe sulfona + Aldicarbe sulfóxido","unidade":"µg/L","maximo":10,"categoria":"Agrotóxicos e metabólitos","referencia":"Anexo 9"},
  {"nome":"Aldrin + Dieldrin","unidade":"µg/L","maximo":0.03,"categoria":"Agrotóxicos e metabólitos","referencia":"Anexo 9"},
  {"nome":"Ametrina","unidade":"µg/L","maximo":60,"categoria":"Agrotóxicos e metabólitos","referencia":"Anexo 9"},
  {"nome":"Atrazina + S-Clorotriazinas","unidade":"µg/L","maximo":2,"categoria":"Agrotóxicos e metabólitos","criterio":"Soma de atrazina e metabólitos S-clorotriazinas","referencia":"Anexo 9"},
  {"nome":"Carbendazim","unidade":"µg/L","maximo":120,"categoria":"Agrotóxicos e metabólitos","referencia":"Anexo 9"},
  {"nome":"Carbofurano","unidade":"µg/L","maximo":7,"categoria":"Agrotóxicos e metabólitos","referencia":"Anexo 9"},
  {"nome":"Ciproconazol","unidade":"µg/L","maximo":30,"categoria":"Agrotóxicos e metabólitos","referencia":"Anexo 9"},
  {"nome":"Clordano","unidade":"µg/L","maximo":0.2,"categoria":"Agrotóxicos e metabólitos","referencia":"Anexo 9"},
  {"nome":"Clorotalonil","unidade":"µg/L","maximo":45,"categoria":"Agrotóxicos e metabólitos","referencia":"Anexo 9"},
  {"nome":"Clorpirifós + Clorpirifós-oxon","unidade":"µg/L","maximo":30,"categoria":"Agrotóxicos e metabólitos","referencia":"Anexo 9"},
  {"nome":"DDT + DDD + DDE","unidade":"µg/L","maximo":1,"categoria":"Agrotóxicos e metabólitos","referencia":"Anexo 9"},
  {"nome":"Difenoconazol","unidade":"µg/L","maximo":30,"categoria":"Agrotóxicos e metabólitos","referencia":"Anexo 9"},
  {"nome":"Dimetoato + Ometoato","unidade":"µg/L","maximo":1.2,"categoria":"Agrotóxicos e metabólitos","referencia":"Anexo 9"},
  {"nome":"Diuron","unidade":"µg/L","maximo":20,"categoria":"Agrotóxicos e metabólitos","referencia":"Anexo 9"},
  {"nome":"Epoxiconazol","unidade":"µg/L","maximo":60,"categoria":"Agrotóxicos e metabólitos","referencia":"Anexo 9"},
  {"nome":"Fipronil","unidade":"µg/L","maximo":1.2,"categoria":"Agrotóxicos e metabólitos","referencia":"Anexo 9"},
  {"nome":"Flutriafol","unidade":"µg/L","maximo":30,"categoria":"Agrotóxicos e metabólitos","referencia":"Anexo 9"},
  {"nome":"Glifosato + AMPA","unidade":"µg/L","maximo":500,"categoria":"Agrotóxicos e metabólitos","referencia":"Anexo 9"},
  {"nome":"Hidroxi-Atrazina","unidade":"µg/L","maximo":120,"categoria":"Agrotóxicos e metabólitos","referencia":"Anexo 9"},
  {"nome":"Lindano (gama-HCH)","unidade":"µg/L","maximo":2,"categoria":"Agrotóxicos e metabólitos","referencia":"Anexo 9"},
  {"nome":"Malationa","unidade":"µg/L","maximo":60,"categoria":"Agrotóxicos e metabólitos","referencia":"Anexo 9"},
  {"nome":"Mancozebe + ETU","unidade":"µg/L","maximo":8,"categoria":"Agrotóxicos e metabólitos","referencia":"Anexo 9"},
  {"nome":"Metamidofós + Acefato","unidade":"µg/L","maximo":7,"categoria":"Agrotóxicos e metabólitos","referencia":"Anexo 9"},
  {"nome":"Metolacloro","unidade":"µg/L","maximo":10,"categoria":"Agrotóxicos e metabólitos","referencia":"Anexo 9"},
  {"nome":"Metribuzim","unidade":"µg/L","maximo":25,"categoria":"Agrotóxicos e metabólitos","referencia":"Anexo 9"},
  {"nome":"Molinato","unidade":"µg/L","maximo":6,"categoria":"Agrotóxicos e metabólitos","referencia":"Anexo 9"},
  {"nome":"Paraquate","unidade":"µg/L","maximo":13,"categoria":"Agrotóxicos e metabólitos","referencia":"Anexo 9"},
  {"nome":"Picloram","unidade":"µg/L","maximo":60,"categoria":"Agrotóxicos e metabólitos","referencia":"Anexo 9"},
  {"nome":"Profenofós","unidade":"µg/L","maximo":0.3,"categoria":"Agrotóxicos e metabólitos","referencia":"Anexo 9"},
  {"nome":"Propargito","unidade":"µg/L","maximo":30,"categoria":"Agrotóxicos e metabólitos","referencia":"Anexo 9"},
  {"nome":"Protioconazol + Protioconazol-destio","unidade":"µg/L","maximo":3,"categoria":"Agrotóxicos e metabólitos","referencia":"Anexo 9"},
  {"nome":"Simazina","unidade":"µg/L","maximo":2,"categoria":"Agrotóxicos e metabólitos","referencia":"Anexo 9"},
  {"nome":"Tebuconazol","unidade":"µg/L","maximo":180,"categoria":"Agrotóxicos e metabólitos","referencia":"Anexo 9"},
  {"nome":"Terbufós","unidade":"µg/L","maximo":1.2,"categoria":"Agrotóxicos e metabólitos","referencia":"Anexo 9"},
  {"nome":"Tiametoxam","unidade":"µg/L","maximo":36,"categoria":"Agrotóxicos e metabólitos","referencia":"Anexo 9"},
  {"nome":"Tiodicarbe","unidade":"µg/L","maximo":90,"categoria":"Agrotóxicos e metabólitos","referencia":"Anexo 9"},
  {"nome":"Tiram","unidade":"µg/L","maximo":6,"categoria":"Agrotóxicos e metabólitos","referencia":"Anexo 9"},
  {"nome":"Trifluralina","unidade":"µg/L","maximo":20,"categoria":"Agrotóxicos e metabólitos","referencia":"Anexo 9"},
  {"nome":"2,4,6-Triclorofenol","unidade":"mg/L","maximo":0.2,"categoria":"Subprodutos da desinfecção","referencia":"Anexo 9"},
  {"nome":"2,4-Diclorofenol","unidade":"mg/L","maximo":0.2,"categoria":"Subprodutos da desinfecção","referencia":"Anexo 9"},
  {"nome":"Ácidos haloacéticos total","unidade":"mg/L","maximo":0.08,"categoria":"Subprodutos da desinfecção","referencia":"Anexo 9"},
  {"nome":"Bromato","unidade":"mg/L","maximo":0.01,"categoria":"Subprodutos da desinfecção","referencia":"Anexo 9"},
  {"nome":"Cloraminas total","unidade":"mg/L","maximo":4,"categoria":"Subprodutos da desinfecção","referencia":"Anexo 9"},
  {"nome":"Clorato","unidade":"mg/L","maximo":0.7,"categoria":"Subprodutos da desinfecção","referencia":"Anexo 9"},
  {"nome":"Clorito","unidade":"mg/L","maximo":0.7,"categoria":"Subprodutos da desinfecção","referencia":"Anexo 9"},
  {"nome":"Cloro residual livre","unidade":"mg/L","minimo":0.2,"maximo":5,"categoria":"Desinfecção","tipo_limite":"faixa","criterio":"Mínimo de 0,2 mg/L em toda a extensão do sistema de distribuição; VMP de 5 mg/L","referencia":"Art. 32 e Anexo 9"},
  {"nome":"Dióxido de cloro residual","unidade":"mg/L","minimo":0.2,"categoria":"Desinfecção","tipo_limite":"minimo","criterio":"Mínimo no sistema de distribuição quando empregado como desinfetante","referencia":"Art. 32"},
  {"nome":"N-Nitrosodimetilamina","unidade":"mg/L","maximo":0.0001,"categoria":"Subprodutos da desinfecção","referencia":"Anexo 9"},
  {"nome":"Trihalometanos total","unidade":"mg/L","maximo":0.1,"categoria":"Subprodutos da desinfecção","referencia":"Anexo 9"},
  {"nome":"Cilindrospermopsinas","unidade":"µg/L","maximo":1,"categoria":"Cianotoxinas","referencia":"Anexo 10"},
  {"nome":"Microcistinas","unidade":"µg/L","maximo":1,"categoria":"Cianotoxinas","referencia":"Anexo 10"},
  {"nome":"Saxitoxinas","unidade":"µg/L","maximo":3,"categoria":"Cianotoxinas","referencia":"Anexo 10"},
  {"nome":"Alumínio","unidade":"mg/L","maximo":0.2,"categoria":"Organolépticos","referencia":"Anexo 11"},
  {"nome":"Amônia (como N)","unidade":"mg/L","maximo":1.2,"categoria":"Organolépticos","referencia":"Anexo 11"},
  {"nome":"Cloreto","unidade":"mg/L","maximo":250,"categoria":"Organolépticos","referencia":"Anexo 11"},
  {"nome":"Cor aparente","unidade":"uH","maximo":15,"categoria":"Organolépticos","referencia":"Anexo 11"},
  {"nome":"1,2-Diclorobenzeno","unidade":"mg/L","maximo":0.001,"categoria":"Organolépticos","referencia":"Anexo 11"},
  {"nome":"1,4-Diclorobenzeno","unidade":"mg/L","maximo":0.0003,"categoria":"Organolépticos","referencia":"Anexo 11"},
  {"nome":"Dureza total","unidade":"mg/L","maximo":300,"categoria":"Organolépticos","referencia":"Anexo 11"},
  {"nome":"Ferro","unidade":"mg/L","maximo":0.3,"categoria":"Organolépticos","referencia":"Anexo 11"},
  {"nome":"Gosto e odor","unidade":"Intensidade","maximo":6,"categoria":"Organolépticos","referencia":"Anexo 11"},
  {"nome":"Manganês","unidade":"mg/L","maximo":0.1,"categoria":"Organolépticos","referencia":"Anexo 11"},
  {"nome":"Monoclorobenzeno","unidade":"mg/L","maximo":0.02,"categoria":"Organolépticos","referencia":"Anexo 11"},
  {"nome":"Sódio","unidade":"mg/L","maximo":200,"categoria":"Organolépticos","referencia":"Anexo 11"},
  {"nome":"Sólidos dissolvidos totais","unidade":"mg/L","maximo":500,"categoria":"Organolépticos","referencia":"Anexo 11"},
  {"nome":"Sulfato","unidade":"mg/L","maximo":250,"categoria":"Organolépticos","referencia":"Anexo 11"},
  {"nome":"Sulfeto de hidrogênio","unidade":"mg/L","maximo":0.05,"categoria":"Organolépticos","referencia":"Anexo 11"},
  {"nome":"Turbidez","unidade":"uT","maximo":5,"categoria":"Organolépticos","criterio":"VMP no sistema de distribuição e pontos de consumo. Metas de filtração do Anexo 2 são específicas do processo de tratamento.","referencia":"Anexo 11"},
  {"nome":"Zinco","unidade":"mg/L","maximo":5,"categoria":"Organolépticos","referencia":"Anexo 11"}
]
$json$::jsonb);

-- Águas salobras compartilham grande parte da Tabela IV; os itens que não
-- pertencem à Tabela VII são removidos e os valores próprios são sobrescritos.
select pg_temp.clone_legal_params('C357_SALINA_1', 'C357_SALOBRA_1');
delete from public.parametro p
using public.legislacao_contexto c
where p.contexto_legislacao_id = c.id
  and c.codigo = 'C357_SALOBRA_1'
  and p.nome in ('Bário total', 'Tálio total', 'Urânio total');

select pg_temp.add_legal_params('C357_SALOBRA_1', $json$
[
  {"nome":"Oxigênio dissolvido","unidade":"mg/L O₂","minimo":5,"categoria":"Condições de qualidade","tipo_limite":"minimo","referencia":"Art. 21, I, c"},
  {"nome":"pH","unidade":"unidade de pH","minimo":6.5,"maximo":8.5,"categoria":"Condições de qualidade","referencia":"Art. 21, I, d"},
  {"nome":"Coliformes termotolerantes — irrigação com contato direto","unidade":"NMP/100 mL","maximo":200,"categoria":"Microbiológicos","criterio":"Irrigação de hortaliças e frutas consumidas cruas e de parques, jardins, esporte e lazer com contato direto","referencia":"Art. 21, I, i"},
  {"nome":"Alumínio dissolvido","unidade":"mg/L Al","maximo":0.1,"categoria":"Inorgânicos","referencia":"Art. 21, II; Tabela VII"},
  {"nome":"Boro total","unidade":"mg/L B","maximo":0.5,"categoria":"Inorgânicos","referencia":"Art. 21, II; Tabela VII"},
  {"nome":"Fósforo total","unidade":"mg/L P","maximo":0.124,"categoria":"Nutrientes","referencia":"Art. 21, II; Tabela VII"},
  {"nome":"Polifosfatos","unidade":"mg/L P","maximo":0.062,"categoria":"Nutrientes","criterio":"Diferença entre fósforo ácido hidrolisável total e fósforo reativo total","referencia":"Art. 21, II; Tabela VII"},
  {"nome":"2,4-D","unidade":"µg/L","maximo":10,"categoria":"Orgânicos","referencia":"Art. 21, II; Tabela VII"},
  {"nome":"Fenóis totais (4-aminoantipirina)","unidade":"mg/L C₆H₅OH","maximo":0.003,"categoria":"Orgânicos","referencia":"Art. 21, II; Tabela VII"},
  {"nome":"Paration","unidade":"µg/L","maximo":0.04,"categoria":"Orgânicos","referencia":"Art. 21, II; Tabela VII"}
]
$json$::jsonb);

select pg_temp.clone_legal_params('C357_SALOBRA_1', 'C357_SALOBRA_1_AQUICULTURA');
select pg_temp.add_legal_params('C357_SALOBRA_1_AQUICULTURA', $json$
[
  {"nome":"Arsênio total","unidade":"µg/L As","maximo":0.14,"categoria":"Pesca/cultivo intensivo","referencia":"Art. 21, III; Tabela VIII"},
  {"nome":"Benzeno","unidade":"µg/L","maximo":51,"categoria":"Pesca/cultivo intensivo","referencia":"Art. 21, III; Tabela VIII"},
  {"nome":"Benzidina","unidade":"µg/L","maximo":0.0002,"categoria":"Pesca/cultivo intensivo","referencia":"Art. 21, III; Tabela VIII"},
  {"nome":"Benzo(a)antraceno","unidade":"µg/L","maximo":0.018,"categoria":"Pesca/cultivo intensivo","referencia":"Art. 21, III; Tabela VIII"},
  {"nome":"Benzo(a)pireno","unidade":"µg/L","maximo":0.018,"categoria":"Pesca/cultivo intensivo","referencia":"Art. 21, III; Tabela VIII"},
  {"nome":"Benzo(b)fluoranteno","unidade":"µg/L","maximo":0.018,"categoria":"Pesca/cultivo intensivo","referencia":"Art. 21, III; Tabela VIII"},
  {"nome":"Benzo(k)fluoranteno","unidade":"µg/L","maximo":0.018,"categoria":"Pesca/cultivo intensivo","referencia":"Art. 21, III; Tabela VIII"},
  {"nome":"Criseno","unidade":"µg/L","maximo":0.018,"categoria":"Pesca/cultivo intensivo","referencia":"Art. 21, III; Tabela VIII"},
  {"nome":"Dibenzo(a,h)antraceno","unidade":"µg/L","maximo":0.018,"categoria":"Pesca/cultivo intensivo","referencia":"Art. 21, III; Tabela VIII"},
  {"nome":"2,4-Diclorofenol","unidade":"µg/L","maximo":290,"categoria":"Pesca/cultivo intensivo","referencia":"Art. 21, III; Tabela VIII"},
  {"nome":"1,1-Dicloroeteno","unidade":"µg/L","maximo":3,"categoria":"Pesca/cultivo intensivo","referencia":"Art. 21, III; Tabela VIII"},
  {"nome":"1,2-Dicloroetano","unidade":"µg/L","maximo":37,"categoria":"Pesca/cultivo intensivo","referencia":"Art. 21, III; Tabela VIII"},
  {"nome":"3,3-Diclorobenzidina","unidade":"µg/L","maximo":0.028,"categoria":"Pesca/cultivo intensivo","referencia":"Art. 21, III; Tabela VIII"},
  {"nome":"Heptacloro epóxido + Heptacloro","unidade":"µg/L","maximo":0.000039,"categoria":"Pesca/cultivo intensivo","referencia":"Art. 21, III; Tabela VIII"},
  {"nome":"Hexaclorobenzeno","unidade":"µg/L","maximo":0.00029,"categoria":"Pesca/cultivo intensivo","referencia":"Art. 21, III; Tabela VIII"},
  {"nome":"Indeno(1,2,3-cd)pireno","unidade":"µg/L","maximo":0.018,"categoria":"Pesca/cultivo intensivo","referencia":"Art. 21, III; Tabela VIII"},
  {"nome":"Pentaclorofenol","unidade":"µg/L","maximo":3,"categoria":"Pesca/cultivo intensivo","referencia":"Art. 21, III; Tabela VIII"},
  {"nome":"PCBs — Bifenilas policloradas","unidade":"µg/L","maximo":0.000064,"categoria":"Pesca/cultivo intensivo","referencia":"Art. 21, III; Tabela VIII"},
  {"nome":"Tetracloroeteno","unidade":"µg/L","maximo":3.3,"categoria":"Pesca/cultivo intensivo","referencia":"Art. 21, III; Tabela VIII"},
  {"nome":"Tricloroeteno","unidade":"µg/L","maximo":30,"categoria":"Pesca/cultivo intensivo","referencia":"Art. 21, III; Tabela VIII"},
  {"nome":"2,4,6-Triclorofenol","unidade":"µg/L","maximo":2.4,"categoria":"Pesca/cultivo intensivo","referencia":"Art. 21, III; Tabela VIII"}
]
$json$::jsonb);

select pg_temp.clone_legal_params('C357_SALOBRA_1', 'C357_SALOBRA_2');
select pg_temp.add_legal_params('C357_SALOBRA_2', $json$
[
  {"nome":"Carbono orgânico total","unidade":"mg/L C","maximo":5,"categoria":"Condições de qualidade","referencia":"Art. 22, I, b"},
  {"nome":"Oxigênio dissolvido","unidade":"mg/L O₂","minimo":4,"categoria":"Condições de qualidade","tipo_limite":"minimo","referencia":"Art. 22, I, c"},
  {"nome":"Coliformes termotolerantes — demais usos","unidade":"NMP/100 mL","maximo":2500,"categoria":"Microbiológicos","criterio":"Não exceder em 80% ou mais de pelo menos 6 amostras anuais, com frequência bimestral","referencia":"Art. 22, I, d"},
  {"nome":"Arsênio total","unidade":"mg/L As","maximo":0.069,"categoria":"Inorgânicos","referencia":"Art. 22, II; Tabela IX"},
  {"nome":"Cádmio total","unidade":"mg/L Cd","maximo":0.04,"categoria":"Inorgânicos","referencia":"Art. 22, II; Tabela IX"},
  {"nome":"Chumbo total","unidade":"mg/L Pb","maximo":0.21,"categoria":"Inorgânicos","referencia":"Art. 22, II; Tabela IX"},
  {"nome":"Cromo total","unidade":"mg/L Cr","maximo":1.1,"categoria":"Inorgânicos","referencia":"Art. 22, II; Tabela IX"},
  {"nome":"Cianeto livre","unidade":"mg/L CN","maximo":0.001,"categoria":"Inorgânicos","referencia":"Art. 22, II; Tabela IX"},
  {"nome":"Cloro residual total (combinado + livre)","unidade":"µg/L Cl","maximo":19,"categoria":"Inorgânicos","referencia":"Art. 22, II; Tabela IX"},
  {"nome":"Cobre dissolvido","unidade":"µg/L Cu","maximo":7.8,"categoria":"Inorgânicos","referencia":"Art. 22, II; Tabela IX"},
  {"nome":"Fósforo total","unidade":"mg/L P","maximo":0.186,"categoria":"Nutrientes","referencia":"Art. 22, II; Tabela IX"},
  {"nome":"Mercúrio total","unidade":"µg/L Hg","maximo":1.8,"categoria":"Inorgânicos","referencia":"Art. 22, II; Tabela IX"},
  {"nome":"Níquel total","unidade":"µg/L Ni","maximo":74,"categoria":"Inorgânicos","referencia":"Art. 22, II; Tabela IX"},
  {"nome":"Nitrato","unidade":"mg/L N","maximo":0.7,"categoria":"Nutrientes","referencia":"Art. 22, II; Tabela IX"},
  {"nome":"Nitrito","unidade":"mg/L N","maximo":0.2,"categoria":"Nutrientes","referencia":"Art. 22, II; Tabela IX"},
  {"nome":"Nitrogênio amoniacal total","unidade":"mg/L N","maximo":0.7,"categoria":"Nutrientes","referencia":"Art. 22, II; Tabela IX"},
  {"nome":"Polifosfatos","unidade":"mg/L P","maximo":0.093,"categoria":"Nutrientes","criterio":"Diferença entre fósforo ácido hidrolisável total e fósforo reativo total","referencia":"Art. 22, II; Tabela IX"},
  {"nome":"Selênio total","unidade":"mg/L Se","maximo":0.29,"categoria":"Inorgânicos","referencia":"Art. 22, II; Tabela IX"},
  {"nome":"Zinco total","unidade":"mg/L Zn","maximo":0.12,"categoria":"Inorgânicos","referencia":"Art. 22, II; Tabela IX"},
  {"nome":"Aldrin + Dieldrin","unidade":"µg/L","maximo":0.03,"categoria":"Orgânicos","referencia":"Art. 22, II; Tabela IX"},
  {"nome":"Clordano (cis + trans)","unidade":"µg/L","maximo":0.09,"categoria":"Orgânicos","referencia":"Art. 22, II; Tabela IX"},
  {"nome":"DDT (p,p'-DDT + p,p'-DDE + p,p'-DDD)","unidade":"µg/L","maximo":0.13,"categoria":"Orgânicos","referencia":"Art. 22, II; Tabela IX"},
  {"nome":"Endrin","unidade":"µg/L","maximo":0.037,"categoria":"Orgânicos","referencia":"Art. 22, II; Tabela IX"},
  {"nome":"Heptacloro epóxido + Heptacloro","unidade":"µg/L","maximo":0.053,"categoria":"Orgânicos","referencia":"Art. 22, II; Tabela IX"},
  {"nome":"Lindano (γ-HCH)","unidade":"µg/L","maximo":0.16,"categoria":"Orgânicos","referencia":"Art. 22, II; Tabela IX"},
  {"nome":"Pentaclorofenol","unidade":"µg/L","maximo":13,"categoria":"Orgânicos","referencia":"Art. 22, II; Tabela IX"},
  {"nome":"Toxafeno","unidade":"µg/L","maximo":0.21,"categoria":"Orgânicos","referencia":"Art. 22, II; Tabela IX"},
  {"nome":"Tributilestanho","unidade":"µg/L TBT","maximo":0.37,"categoria":"Orgânicos","referencia":"Art. 22, II; Tabela IX"}
]
$json$::jsonb);

select pg_temp.add_legal_params('C357_SALOBRA_3', $json$
[
  {"nome":"pH","unidade":"unidade de pH","minimo":5,"maximo":9,"categoria":"Condições de qualidade","referencia":"Art. 23, I"},
  {"nome":"Oxigênio dissolvido","unidade":"mg/L O₂","minimo":3,"categoria":"Condições de qualidade","tipo_limite":"minimo","referencia":"Art. 23, II"},
  {"nome":"Óleos e graxas","unidade":"Presença/ausência","categoria":"Condições de qualidade","tipo_resultado":"qualitativo","tipo_limite":"informativo","criterio":"Toleram-se iridescências","referencia":"Art. 23, III"},
  {"nome":"Materiais flutuantes e substâncias sedimentáveis objetáveis","unidade":"Presença/ausência","categoria":"Condições de qualidade","tipo_resultado":"qualitativo","tipo_limite":"ausencia","criterio":"Virtualmente ausentes","referencia":"Art. 23, IV a VI"},
  {"nome":"Coliformes termotolerantes","unidade":"NMP/100 mL","maximo":4000,"categoria":"Microbiológicos","criterio":"Não exceder em 80% ou mais de pelo menos 6 amostras anuais, com frequência bimestral","referencia":"Art. 23, VII"},
  {"nome":"Carbono orgânico total","unidade":"mg/L C","maximo":10,"categoria":"Condições de qualidade","referencia":"Art. 23, VIII"}
]
$json$::jsonb);

alter table public.legislacao_contexto enable row level security;
revoke all on table public.legislacao_contexto from anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;

-- Agora todo parâmetro legal semeado deve possuir contexto explícito.
alter table public.parametro alter column contexto_legislacao_id set not null;

select pg_temp.clone_legal_params('C357_SALINA_1', 'C357_SALINA_1_AQUICULTURA');
select pg_temp.add_legal_params('C357_SALINA_1_AQUICULTURA', $json$
[
  {"nome":"Arsênio total","unidade":"µg/L As","maximo":0.14,"categoria":"Pesca/cultivo intensivo","referencia":"Art. 18, III; Tabela V"},
  {"nome":"Benzeno","unidade":"µg/L","maximo":51,"categoria":"Pesca/cultivo intensivo","referencia":"Art. 18, III; Tabela V"},
  {"nome":"Benzidina","unidade":"µg/L","maximo":0.0002,"categoria":"Pesca/cultivo intensivo","referencia":"Art. 18, III; Tabela V"},
  {"nome":"Benzo(a)antraceno","unidade":"µg/L","maximo":0.018,"categoria":"Pesca/cultivo intensivo","referencia":"Art. 18, III; Tabela V"},
  {"nome":"Benzo(a)pireno","unidade":"µg/L","maximo":0.018,"categoria":"Pesca/cultivo intensivo","referencia":"Art. 18, III; Tabela V"},
  {"nome":"Benzo(b)fluoranteno","unidade":"µg/L","maximo":0.018,"categoria":"Pesca/cultivo intensivo","referencia":"Art. 18, III; Tabela V"},
  {"nome":"Benzo(k)fluoranteno","unidade":"µg/L","maximo":0.018,"categoria":"Pesca/cultivo intensivo","referencia":"Art. 18, III; Tabela V"},
  {"nome":"2-Clorofenol","unidade":"µg/L","maximo":150,"categoria":"Pesca/cultivo intensivo","referencia":"Art. 18, III; Tabela V"},
  {"nome":"2,4-Diclorofenol","unidade":"µg/L","maximo":290,"categoria":"Pesca/cultivo intensivo","referencia":"Art. 18, III; Tabela V"},
  {"nome":"Criseno","unidade":"µg/L","maximo":0.018,"categoria":"Pesca/cultivo intensivo","referencia":"Art. 18, III; Tabela V"},
  {"nome":"Dibenzo(a,h)antraceno","unidade":"µg/L","maximo":0.018,"categoria":"Pesca/cultivo intensivo","referencia":"Art. 18, III; Tabela V"},
  {"nome":"1,2-Dicloroetano","unidade":"µg/L","maximo":37,"categoria":"Pesca/cultivo intensivo","referencia":"Art. 18, III; Tabela V"},
  {"nome":"1,1-Dicloroeteno","unidade":"µg/L","maximo":3,"categoria":"Pesca/cultivo intensivo","referencia":"Art. 18, III; Tabela V"},
  {"nome":"3,3-Diclorobenzidina","unidade":"µg/L","maximo":0.028,"categoria":"Pesca/cultivo intensivo","referencia":"Art. 18, III; Tabela V"},
  {"nome":"Heptacloro epóxido + Heptacloro","unidade":"µg/L","maximo":0.000039,"categoria":"Pesca/cultivo intensivo","referencia":"Art. 18, III; Tabela V"},
  {"nome":"Hexaclorobenzeno","unidade":"µg/L","maximo":0.00029,"categoria":"Pesca/cultivo intensivo","referencia":"Art. 18, III; Tabela V"},
  {"nome":"Indeno(1,2,3-cd)pireno","unidade":"µg/L","maximo":0.018,"categoria":"Pesca/cultivo intensivo","referencia":"Art. 18, III; Tabela V"},
  {"nome":"PCBs — Bifenilas policloradas","unidade":"µg/L","maximo":0.000064,"categoria":"Pesca/cultivo intensivo","referencia":"Art. 18, III; Tabela V"},
  {"nome":"Pentaclorofenol","unidade":"µg/L","maximo":3,"categoria":"Pesca/cultivo intensivo","referencia":"Art. 18, III; Tabela V"},
  {"nome":"Tetracloroeteno","unidade":"µg/L","maximo":3.3,"categoria":"Pesca/cultivo intensivo","referencia":"Art. 18, III; Tabela V"},
  {"nome":"2,4,6-Triclorofenol","unidade":"µg/L","maximo":2.4,"categoria":"Pesca/cultivo intensivo","referencia":"Art. 18, III; Tabela V"}
]
$json$::jsonb);

select pg_temp.clone_legal_params('C357_SALINA_1', 'C357_SALINA_2');
select pg_temp.add_legal_params('C357_SALINA_2', $json$
[
  {"nome":"Carbono orgânico total","unidade":"mg/L C","maximo":5,"categoria":"Condições de qualidade","referencia":"Art. 19, I"},
  {"nome":"Oxigênio dissolvido","unidade":"mg/L O₂","minimo":5,"categoria":"Condições de qualidade","tipo_limite":"minimo","referencia":"Art. 19, I"},
  {"nome":"Coliformes termotolerantes — demais usos","unidade":"NMP/100 mL","maximo":2500,"categoria":"Microbiológicos","criterio":"Não exceder em 80% ou mais de pelo menos 6 amostras anuais, com frequência bimestral","referencia":"Art. 19, I"},
  {"nome":"Arsênio total","unidade":"mg/L As","maximo":0.069,"categoria":"Inorgânicos","referencia":"Art. 19, II; Tabela VI"},
  {"nome":"Cádmio total","unidade":"mg/L Cd","maximo":0.04,"categoria":"Inorgânicos","referencia":"Art. 19, II; Tabela VI"},
  {"nome":"Chumbo total","unidade":"mg/L Pb","maximo":0.21,"categoria":"Inorgânicos","referencia":"Art. 19, II; Tabela VI"},
  {"nome":"Cianeto livre","unidade":"mg/L CN","maximo":0.001,"categoria":"Inorgânicos","referencia":"Art. 19, II; Tabela VI"},
  {"nome":"Cloro residual total (combinado + livre)","unidade":"µg/L Cl","maximo":19,"categoria":"Inorgânicos","referencia":"Art. 19, II; Tabela VI"},
  {"nome":"Cobre dissolvido","unidade":"µg/L Cu","maximo":7.8,"categoria":"Inorgânicos","referencia":"Art. 19, II; Tabela VI"},
  {"nome":"Cromo total","unidade":"mg/L Cr","maximo":1.1,"categoria":"Inorgânicos","referencia":"Art. 19, II; Tabela VI"},
  {"nome":"Fósforo total","unidade":"mg/L P","maximo":0.093,"categoria":"Nutrientes","referencia":"Art. 19, II; Tabela VI"},
  {"nome":"Mercúrio total","unidade":"µg/L Hg","maximo":1.8,"categoria":"Inorgânicos","referencia":"Art. 19, II; Tabela VI"},
  {"nome":"Níquel total","unidade":"µg/L Ni","maximo":74,"categoria":"Inorgânicos","referencia":"Art. 19, II; Tabela VI"},
  {"nome":"Nitrato","unidade":"mg/L N","maximo":0.7,"categoria":"Nutrientes","referencia":"Art. 19, II; Tabela VI"},
  {"nome":"Nitrito","unidade":"mg/L N","maximo":0.2,"categoria":"Nutrientes","referencia":"Art. 19, II; Tabela VI"},
  {"nome":"Nitrogênio amoniacal total","unidade":"mg/L N","maximo":0.7,"categoria":"Nutrientes","referencia":"Art. 19, II; Tabela VI"},
  {"nome":"Polifosfatos","unidade":"mg/L P","maximo":0.0465,"categoria":"Nutrientes","criterio":"Diferença entre fósforo ácido hidrolisável total e fósforo reativo total","referencia":"Art. 19, II; Tabela VI"},
  {"nome":"Selênio total","unidade":"mg/L Se","maximo":0.29,"categoria":"Inorgânicos","referencia":"Art. 19, II; Tabela VI"},
  {"nome":"Zinco total","unidade":"mg/L Zn","maximo":0.12,"categoria":"Inorgânicos","referencia":"Art. 19, II; Tabela VI"},
  {"nome":"Aldrin + Dieldrin","unidade":"µg/L","maximo":0.03,"categoria":"Orgânicos","referencia":"Art. 19, II; Tabela VI"},
  {"nome":"Clordano (cis + trans)","unidade":"µg/L","maximo":0.09,"categoria":"Orgânicos","referencia":"Art. 19, II; Tabela VI"},
  {"nome":"DDT (p,p'-DDT + p,p'-DDE + p,p'-DDD)","unidade":"µg/L","maximo":0.13,"categoria":"Orgânicos","referencia":"Art. 19, II; Tabela VI"},
  {"nome":"Endrin","unidade":"µg/L","maximo":0.037,"categoria":"Orgânicos","referencia":"Art. 19, II; Tabela VI"},
  {"nome":"Heptacloro epóxido + Heptacloro","unidade":"µg/L","maximo":0.053,"categoria":"Orgânicos","referencia":"Art. 19, II; Tabela VI"},
  {"nome":"Lindano (γ-HCH)","unidade":"µg/L","maximo":0.16,"categoria":"Orgânicos","referencia":"Art. 19, II; Tabela VI"},
  {"nome":"Pentaclorofenol","unidade":"µg/L","maximo":13,"categoria":"Orgânicos","referencia":"Art. 19, II; Tabela VI"},
  {"nome":"Toxafeno","unidade":"µg/L","maximo":0.21,"categoria":"Orgânicos","referencia":"Art. 19, II; Tabela VI"},
  {"nome":"Tributilestanho","unidade":"µg/L TBT","maximo":0.37,"categoria":"Orgânicos","referencia":"Art. 19, II; Tabela VI"}
]
$json$::jsonb);

select pg_temp.add_legal_params('C357_SALINA_3', $json$
[
  {"nome":"Carbono orgânico total","unidade":"mg/L C","maximo":10,"categoria":"Condições de qualidade","referencia":"Art. 20, VII"},
  {"nome":"Oxigênio dissolvido","unidade":"mg/L O₂","minimo":4,"categoria":"Condições de qualidade","tipo_limite":"minimo","referencia":"Art. 20, VIII"},
  {"nome":"pH","unidade":"unidade de pH","minimo":6.5,"maximo":8.5,"categoria":"Condições de qualidade","criterio":"A mudança do pH natural não deve ser maior que 0,2 unidade","referencia":"Art. 20, IX"},
  {"nome":"Coliformes termotolerantes","unidade":"NMP/100 mL","maximo":4000,"categoria":"Microbiológicos","criterio":"Não exceder em 80% ou mais de pelo menos 6 amostras anuais, com frequência bimestral","referencia":"Art. 20, VI"},
  {"nome":"Materiais flutuantes, espumas, corantes e resíduos objetáveis","unidade":"Presença/ausência","categoria":"Condições de qualidade","tipo_resultado":"qualitativo","tipo_limite":"ausencia","criterio":"Virtualmente ausentes","referencia":"Art. 20, I, III, IV e V"},
  {"nome":"Óleos e graxas","unidade":"Presença/ausência","categoria":"Condições de qualidade","tipo_resultado":"qualitativo","tipo_limite":"informativo","criterio":"Toleram-se iridescências","referencia":"Art. 20, II"}
]
$json$::jsonb);


-- Águas salinas, classe 1.
select pg_temp.add_legal_params('C357_SALINA_1', $json$
[
  {"nome":"Carbono orgânico total","unidade":"mg/L C","maximo":3,"categoria":"Condições de qualidade","referencia":"Art. 18, I"},
  {"nome":"Oxigênio dissolvido","unidade":"mg/L O₂","minimo":6,"categoria":"Condições de qualidade","tipo_limite":"minimo","referencia":"Art. 18, I"},
  {"nome":"pH","unidade":"unidade de pH","minimo":6.5,"maximo":8.5,"categoria":"Condições de qualidade","criterio":"A mudança do pH natural não deve ser maior que 0,2 unidade","referencia":"Art. 18, I"},
  {"nome":"Óleos e graxas","unidade":"Presença/ausência","categoria":"Condições de qualidade","tipo_resultado":"qualitativo","tipo_limite":"ausencia","criterio":"Virtualmente ausentes","referencia":"Art. 18, I"},
  {"nome":"Materiais flutuantes","unidade":"Presença/ausência","categoria":"Condições de qualidade","tipo_resultado":"qualitativo","tipo_limite":"ausencia","criterio":"Virtualmente ausentes","referencia":"Art. 18, I"},
  {"nome":"Substâncias que produzem cor, odor e turbidez","unidade":"Presença/ausência","categoria":"Condições de qualidade","tipo_resultado":"qualitativo","tipo_limite":"ausencia","criterio":"Virtualmente ausentes","referencia":"Art. 18, I"},
  {"nome":"Resíduos sólidos objetáveis","unidade":"Presença/ausência","categoria":"Condições de qualidade","tipo_resultado":"qualitativo","tipo_limite":"ausencia","criterio":"Virtualmente ausentes","referencia":"Art. 18, I"},
  {"nome":"Coliformes termotolerantes — cultivo de moluscos (média geométrica)","unidade":"NMP/100 mL","maximo":43,"categoria":"Microbiológicos","criterio":"Média geométrica de no mínimo 15 amostras; percentil 90 não superior a 88 NMP/100 mL","referencia":"Art. 18, I"},
  {"nome":"Coliformes termotolerantes — demais usos","unidade":"NMP/100 mL","maximo":1000,"categoria":"Microbiológicos","criterio":"Não exceder em 80% ou mais de pelo menos 6 amostras anuais, com frequência bimestral","referencia":"Art. 18, I"},
  {"nome":"Alumínio dissolvido","unidade":"mg/L Al","maximo":1.5,"categoria":"Inorgânicos","referencia":"Art. 18, II; Tabela IV"},
  {"nome":"Arsênio total","unidade":"mg/L As","maximo":0.01,"categoria":"Inorgânicos","referencia":"Art. 18, II; Tabela IV"},
  {"nome":"Bário total","unidade":"mg/L Ba","maximo":1,"categoria":"Inorgânicos","referencia":"Art. 18, II; Tabela IV"},
  {"nome":"Berílio total","unidade":"µg/L Be","maximo":5.3,"categoria":"Inorgânicos","referencia":"Art. 18, II; Tabela IV"},
  {"nome":"Boro total","unidade":"mg/L B","maximo":5,"categoria":"Inorgânicos","referencia":"Art. 18, II; Tabela IV"},
  {"nome":"Cádmio total","unidade":"mg/L Cd","maximo":0.005,"categoria":"Inorgânicos","referencia":"Art. 18, II; Tabela IV"},
  {"nome":"Chumbo total","unidade":"mg/L Pb","maximo":0.01,"categoria":"Inorgânicos","referencia":"Art. 18, II; Tabela IV"},
  {"nome":"Cianeto livre","unidade":"mg/L CN","maximo":0.001,"categoria":"Inorgânicos","referencia":"Art. 18, II; Tabela IV"},
  {"nome":"Cloro residual total (combinado + livre)","unidade":"mg/L Cl","maximo":0.01,"categoria":"Inorgânicos","referencia":"Art. 18, II; Tabela IV"},
  {"nome":"Cobre dissolvido","unidade":"mg/L Cu","maximo":0.005,"categoria":"Inorgânicos","referencia":"Art. 18, II; Tabela IV"},
  {"nome":"Cromo total","unidade":"mg/L Cr","maximo":0.05,"categoria":"Inorgânicos","referencia":"Art. 18, II; Tabela IV"},
  {"nome":"Ferro dissolvido","unidade":"mg/L Fe","maximo":0.3,"categoria":"Inorgânicos","referencia":"Art. 18, II; Tabela IV"},
  {"nome":"Fluoreto total","unidade":"mg/L F","maximo":1.4,"categoria":"Inorgânicos","referencia":"Art. 18, II; Tabela IV"},
  {"nome":"Fósforo total","unidade":"mg/L P","maximo":0.062,"categoria":"Nutrientes","referencia":"Art. 18, II; Tabela IV"},
  {"nome":"Manganês total","unidade":"mg/L Mn","maximo":0.1,"categoria":"Inorgânicos","referencia":"Art. 18, II; Tabela IV"},
  {"nome":"Mercúrio total","unidade":"mg/L Hg","maximo":0.0002,"categoria":"Inorgânicos","referencia":"Art. 18, II; Tabela IV"},
  {"nome":"Níquel total","unidade":"mg/L Ni","maximo":0.025,"categoria":"Inorgânicos","referencia":"Art. 18, II; Tabela IV"},
  {"nome":"Nitrato","unidade":"mg/L N","maximo":0.4,"categoria":"Nutrientes","referencia":"Art. 18, II; Tabela IV"},
  {"nome":"Nitrito","unidade":"mg/L N","maximo":0.07,"categoria":"Nutrientes","referencia":"Art. 18, II; Tabela IV"},
  {"nome":"Nitrogênio amoniacal total","unidade":"mg/L N","maximo":0.4,"categoria":"Nutrientes","referencia":"Art. 18, II; Tabela IV"},
  {"nome":"Polifosfatos","unidade":"mg/L P","maximo":0.031,"categoria":"Nutrientes","criterio":"Diferença entre fósforo ácido hidrolisável total e fósforo reativo total","referencia":"Art. 18, II; Tabela IV"},
  {"nome":"Prata total","unidade":"mg/L Ag","maximo":0.005,"categoria":"Inorgânicos","referencia":"Art. 18, II; Tabela IV"},
  {"nome":"Selênio total","unidade":"mg/L Se","maximo":0.01,"categoria":"Inorgânicos","referencia":"Art. 18, II; Tabela IV"},
  {"nome":"Sulfeto (como H₂S não dissociado)","unidade":"mg/L S","maximo":0.002,"categoria":"Inorgânicos","referencia":"Art. 18, II; Tabela IV"},
  {"nome":"Tálio total","unidade":"mg/L Tl","maximo":0.1,"categoria":"Inorgânicos","referencia":"Art. 18, II; Tabela IV"},
  {"nome":"Urânio total","unidade":"mg/L U","maximo":0.5,"categoria":"Inorgânicos","referencia":"Art. 18, II; Tabela IV"},
  {"nome":"Zinco total","unidade":"mg/L Zn","maximo":0.09,"categoria":"Inorgânicos","referencia":"Art. 18, II; Tabela IV"},
  {"nome":"Aldrin + Dieldrin","unidade":"µg/L","maximo":0.0019,"categoria":"Orgânicos","referencia":"Art. 18, II; Tabela IV"},
  {"nome":"Benzeno","unidade":"µg/L","maximo":700,"categoria":"Orgânicos","referencia":"Art. 18, II; Tabela IV"},
  {"nome":"Carbaril","unidade":"µg/L","maximo":0.32,"categoria":"Orgânicos","referencia":"Art. 18, II; Tabela IV"},
  {"nome":"Clordano (cis + trans)","unidade":"µg/L","maximo":0.004,"categoria":"Orgânicos","referencia":"Art. 18, II; Tabela IV"},
  {"nome":"2,4-D","unidade":"µg/L","maximo":30,"categoria":"Orgânicos","referencia":"Art. 18, II; Tabela IV"},
  {"nome":"DDT (p,p'-DDT + p,p'-DDE + p,p'-DDD)","unidade":"µg/L","maximo":0.001,"categoria":"Orgânicos","referencia":"Art. 18, II; Tabela IV"},
  {"nome":"Demeton (Demeton-O + Demeton-S)","unidade":"µg/L","maximo":0.1,"categoria":"Orgânicos","referencia":"Art. 18, II; Tabela IV"},
  {"nome":"Dodecacloro pentaciclodecano","unidade":"µg/L","maximo":0.001,"categoria":"Orgânicos","referencia":"Art. 18, II; Tabela IV"},
  {"nome":"Endossulfan (α + β + sulfato)","unidade":"µg/L","maximo":0.01,"categoria":"Orgânicos","referencia":"Art. 18, II; Tabela IV"},
  {"nome":"Endrin","unidade":"µg/L","maximo":0.004,"categoria":"Orgânicos","referencia":"Art. 18, II; Tabela IV"},
  {"nome":"Etilbenzeno","unidade":"µg/L","maximo":25,"categoria":"Orgânicos","referencia":"Art. 18, II; Tabela IV"},
  {"nome":"Fenóis totais (4-aminoantipirina)","unidade":"µg/L C₆H₅OH","maximo":60,"categoria":"Orgânicos","referencia":"Art. 18, II; Tabela IV"},
  {"nome":"Gution","unidade":"µg/L","maximo":0.01,"categoria":"Orgânicos","referencia":"Art. 18, II; Tabela IV"},
  {"nome":"Heptacloro epóxido + Heptacloro","unidade":"µg/L","maximo":0.001,"categoria":"Orgânicos","referencia":"Art. 18, II; Tabela IV"},
  {"nome":"Lindano (γ-HCH)","unidade":"µg/L","maximo":0.004,"categoria":"Orgânicos","referencia":"Art. 18, II; Tabela IV"},
  {"nome":"Malation","unidade":"µg/L","maximo":0.1,"categoria":"Orgânicos","referencia":"Art. 18, II; Tabela IV"},
  {"nome":"Metoxicloro","unidade":"µg/L","maximo":0.03,"categoria":"Orgânicos","referencia":"Art. 18, II; Tabela IV"},
  {"nome":"Monoclorobenzeno","unidade":"µg/L","maximo":25,"categoria":"Orgânicos","referencia":"Art. 18, II; Tabela IV"},
  {"nome":"Pentaclorofenol","unidade":"µg/L","maximo":7.9,"categoria":"Orgânicos","referencia":"Art. 18, II; Tabela IV"},
  {"nome":"PCBs — Bifenilas policloradas","unidade":"µg/L","maximo":0.03,"categoria":"Orgânicos","referencia":"Art. 18, II; Tabela IV"},
  {"nome":"Substâncias tensoativas que reagem com azul de metileno","unidade":"mg/L LAS","maximo":0.2,"categoria":"Orgânicos","referencia":"Art. 18, II; Tabela IV"},
  {"nome":"2,4,5-T","unidade":"µg/L","maximo":10,"categoria":"Orgânicos","referencia":"Art. 18, II; Tabela IV"},
  {"nome":"Tolueno","unidade":"µg/L","maximo":215,"categoria":"Orgânicos","referencia":"Art. 18, II; Tabela IV"},
  {"nome":"Toxafeno","unidade":"µg/L","maximo":0.0002,"categoria":"Orgânicos","referencia":"Art. 18, II; Tabela IV"},
  {"nome":"2,4,5-TP","unidade":"µg/L","maximo":10,"categoria":"Orgânicos","referencia":"Art. 18, II; Tabela IV"},
  {"nome":"Tributilestanho","unidade":"µg/L TBT","maximo":0.01,"categoria":"Orgânicos","referencia":"Art. 18, II; Tabela IV"},
  {"nome":"Triclorobenzeno (1,2,3-TCB + 1,2,4-TCB)","unidade":"µg/L","maximo":80,"categoria":"Orgânicos","referencia":"Art. 18, II; Tabela IV"},
  {"nome":"Tricloroeteno","unidade":"µg/L","maximo":30,"categoria":"Orgânicos","referencia":"Art. 18, II; Tabela IV"}
]
$json$::jsonb);


select pg_temp.clone_legal_params('C357_DOCE_1', 'C357_DOCE_1_AQUICULTURA');
select pg_temp.add_legal_params('C357_DOCE_1_AQUICULTURA', $json$
[
  {"nome":"Arsênio total","unidade":"µg/L As","maximo":0.14,"categoria":"Pesca/cultivo intensivo","referencia":"Art. 14, III; Tabela II"},
  {"nome":"Benzidina","unidade":"µg/L","maximo":0.0002,"categoria":"Pesca/cultivo intensivo","referencia":"Art. 14, III; Tabela II"},
  {"nome":"Benzo(a)antraceno","unidade":"µg/L","maximo":0.018,"categoria":"Pesca/cultivo intensivo","referencia":"Art. 14, III; Tabela II"},
  {"nome":"Benzo(a)pireno","unidade":"µg/L","maximo":0.018,"categoria":"Pesca/cultivo intensivo","referencia":"Art. 14, III; Tabela II"},
  {"nome":"Benzo(b)fluoranteno","unidade":"µg/L","maximo":0.018,"categoria":"Pesca/cultivo intensivo","referencia":"Art. 14, III; Tabela II"},
  {"nome":"Benzo(k)fluoranteno","unidade":"µg/L","maximo":0.018,"categoria":"Pesca/cultivo intensivo","referencia":"Art. 14, III; Tabela II"},
  {"nome":"Criseno","unidade":"µg/L","maximo":0.018,"categoria":"Pesca/cultivo intensivo","referencia":"Art. 14, III; Tabela II"},
  {"nome":"Dibenzo(a,h)antraceno","unidade":"µg/L","maximo":0.018,"categoria":"Pesca/cultivo intensivo","referencia":"Art. 14, III; Tabela II"},
  {"nome":"3,3-Diclorobenzidina","unidade":"µg/L","maximo":0.028,"categoria":"Pesca/cultivo intensivo","referencia":"Art. 14, III; Tabela II"},
  {"nome":"Heptacloro epóxido + Heptacloro","unidade":"µg/L","maximo":0.000039,"categoria":"Pesca/cultivo intensivo","referencia":"Art. 14, III; Tabela II"},
  {"nome":"Hexaclorobenzeno","unidade":"µg/L","maximo":0.00029,"categoria":"Pesca/cultivo intensivo","referencia":"Art. 14, III; Tabela II"},
  {"nome":"Indeno(1,2,3-cd)pireno","unidade":"µg/L","maximo":0.018,"categoria":"Pesca/cultivo intensivo","referencia":"Art. 14, III; Tabela II"},
  {"nome":"PCBs — Bifenilas policloradas","unidade":"µg/L","maximo":0.000064,"categoria":"Pesca/cultivo intensivo","referencia":"Art. 14, III; Tabela II"},
  {"nome":"Pentaclorofenol","unidade":"µg/L","maximo":3,"categoria":"Pesca/cultivo intensivo","referencia":"Art. 14, III; Tabela II"},
  {"nome":"Tetracloreto de carbono","unidade":"µg/L","maximo":1.6,"categoria":"Pesca/cultivo intensivo","referencia":"Art. 14, III; Tabela II"},
  {"nome":"Tetracloroeteno","unidade":"µg/L","maximo":3.3,"categoria":"Pesca/cultivo intensivo","referencia":"Art. 14, III; Tabela II"},
  {"nome":"Toxafeno","unidade":"µg/L","maximo":0.00028,"categoria":"Pesca/cultivo intensivo","referencia":"Art. 14, III; Tabela II"},
  {"nome":"2,4,6-Triclorofenol","unidade":"µg/L","maximo":2.4,"categoria":"Pesca/cultivo intensivo","referencia":"Art. 14, III; Tabela II"}
]
$json$::jsonb);

select pg_temp.clone_legal_params('C357_DOCE_1', 'C357_DOCE_2');
select pg_temp.add_legal_params('C357_DOCE_2', $json$
[
  {"nome":"Corantes provenientes de fontes antrópicas","unidade":"Presença/ausência","categoria":"Condições de qualidade","tipo_resultado":"qualitativo","tipo_limite":"ausencia","criterio":"Não permitidos quando não removíveis por coagulação, sedimentação e filtração convencionais","referencia":"Art. 15, I"},
  {"nome":"Coliformes termotolerantes — demais usos","unidade":"NMP/100 mL","maximo":1000,"categoria":"Microbiológicos","criterio":"Não exceder em 80% ou mais de pelo menos 6 amostras anuais, com frequência bimestral; recreação primária segue a CONAMA 274/2000","referencia":"Art. 15, II"},
  {"nome":"Cor verdadeira","unidade":"mg Pt/L","maximo":75,"categoria":"Condições de qualidade","referencia":"Art. 15, III"},
  {"nome":"Turbidez","unidade":"UNT","maximo":100,"categoria":"Condições de qualidade","referencia":"Art. 15, IV"},
  {"nome":"DBO 5 dias, 20 °C","unidade":"mg/L O₂","maximo":5,"categoria":"Condições de qualidade","referencia":"Art. 15, V"},
  {"nome":"Oxigênio dissolvido","unidade":"mg/L O₂","minimo":5,"categoria":"Condições de qualidade","tipo_limite":"minimo","referencia":"Art. 15, VI"},
  {"nome":"Clorofila a","unidade":"µg/L","maximo":30,"categoria":"Biológicos e nutrientes","referencia":"Art. 15, VII"},
  {"nome":"Densidade de cianobactérias","unidade":"células/mL","maximo":50000,"categoria":"Biológicos e nutrientes","criterio":"Alternativamente, até 5 mm³/L de biovolume","referencia":"Art. 15, VIII"},
  {"nome":"Fósforo total — ambiente lêntico","unidade":"mg/L P","maximo":0.03,"categoria":"Biológicos e nutrientes","referencia":"Art. 15, IX"},
  {"nome":"Fósforo total — ambiente intermediário","unidade":"mg/L P","maximo":0.05,"categoria":"Biológicos e nutrientes","criterio":"Ambientes intermediários e tributários diretos de ambiente lêntico","referencia":"Art. 15, IX"}
]
$json$::jsonb);

select pg_temp.add_legal_params('C357_DOCE_3', $json$
[
  {"nome":"Coliformes termotolerantes — recreação de contato secundário","unidade":"NMP/100 mL","maximo":2500,"categoria":"Microbiológicos","criterio":"Não exceder em 80% ou mais de pelo menos 6 amostras anuais, com frequência bimestral","referencia":"Art. 16, I, g"},
  {"nome":"Coliformes termotolerantes — dessedentação de animais","unidade":"NMP/100 mL","maximo":1000,"categoria":"Microbiológicos","criterio":"Não exceder em 80% ou mais de pelo menos 6 amostras anuais, com frequência bimestral","referencia":"Art. 16, I, g"},
  {"nome":"Coliformes termotolerantes — demais usos","unidade":"NMP/100 mL","maximo":4000,"categoria":"Microbiológicos","criterio":"Não exceder em 80% ou mais de pelo menos 6 amostras anuais, com frequência bimestral","referencia":"Art. 16, I, g"},
  {"nome":"DBO 5 dias, 20 °C","unidade":"mg/L O₂","maximo":10,"categoria":"Condições de qualidade","referencia":"Art. 16, I, h"},
  {"nome":"Oxigênio dissolvido","unidade":"mg/L O₂","minimo":4,"categoria":"Condições de qualidade","tipo_limite":"minimo","referencia":"Art. 16, I, i"},
  {"nome":"Turbidez","unidade":"UNT","maximo":100,"categoria":"Condições de qualidade","referencia":"Art. 16, I, j"},
  {"nome":"Cor verdadeira","unidade":"mg Pt/L","maximo":75,"categoria":"Condições de qualidade","referencia":"Art. 16, I, l"},
  {"nome":"pH","unidade":"unidade de pH","minimo":6,"maximo":9,"categoria":"Condições de qualidade","referencia":"Art. 16, I, m"},
  {"nome":"Clorofila a","unidade":"µg/L","maximo":60,"categoria":"Biológicos e nutrientes","referencia":"Art. 16, II; Tabela III"},
  {"nome":"Densidade de cianobactérias","unidade":"células/mL","maximo":100000,"categoria":"Biológicos e nutrientes","criterio":"Alternativamente, até 10 mm³/L de biovolume","referencia":"Art. 16, II; Tabela III"},
  {"nome":"Sólidos dissolvidos totais","unidade":"mg/L","maximo":500,"categoria":"Inorgânicos","referencia":"Art. 16, II; Tabela III"},
  {"nome":"Alumínio dissolvido","unidade":"mg/L Al","maximo":0.2,"categoria":"Inorgânicos","referencia":"Art. 16, II; Tabela III"},
  {"nome":"Arsênio total","unidade":"mg/L As","maximo":0.033,"categoria":"Inorgânicos","referencia":"Art. 16, II; Tabela III"},
  {"nome":"Bário total","unidade":"mg/L Ba","maximo":1,"categoria":"Inorgânicos","referencia":"Art. 16, II; Tabela III"},
  {"nome":"Berílio total","unidade":"mg/L Be","maximo":0.1,"categoria":"Inorgânicos","referencia":"Art. 16, II; Tabela III"},
  {"nome":"Boro total","unidade":"mg/L B","maximo":0.75,"categoria":"Inorgânicos","referencia":"Art. 16, II; Tabela III"},
  {"nome":"Cádmio total","unidade":"mg/L Cd","maximo":0.01,"categoria":"Inorgânicos","referencia":"Art. 16, II; Tabela III"},
  {"nome":"Chumbo total","unidade":"mg/L Pb","maximo":0.033,"categoria":"Inorgânicos","referencia":"Art. 16, II; Tabela III"},
  {"nome":"Cianeto livre","unidade":"mg/L CN","maximo":0.022,"categoria":"Inorgânicos","referencia":"Art. 16, II; Tabela III"},
  {"nome":"Cloreto total","unidade":"mg/L Cl","maximo":250,"categoria":"Inorgânicos","referencia":"Art. 16, II; Tabela III"},
  {"nome":"Cobalto total","unidade":"mg/L Co","maximo":0.2,"categoria":"Inorgânicos","referencia":"Art. 16, II; Tabela III"},
  {"nome":"Cobre dissolvido","unidade":"mg/L Cu","maximo":0.013,"categoria":"Inorgânicos","referencia":"Art. 16, II; Tabela III"},
  {"nome":"Cromo total","unidade":"mg/L Cr","maximo":0.05,"categoria":"Inorgânicos","referencia":"Art. 16, II; Tabela III"},
  {"nome":"Ferro dissolvido","unidade":"mg/L Fe","maximo":5,"categoria":"Inorgânicos","referencia":"Art. 16, II; Tabela III"},
  {"nome":"Fluoreto total","unidade":"mg/L F","maximo":1.4,"categoria":"Inorgânicos","referencia":"Art. 16, II; Tabela III"},
  {"nome":"Fósforo total — ambiente lêntico","unidade":"mg/L P","maximo":0.05,"categoria":"Biológicos e nutrientes","referencia":"Art. 16, II; Tabela III"},
  {"nome":"Fósforo total — ambiente intermediário","unidade":"mg/L P","maximo":0.075,"categoria":"Biológicos e nutrientes","criterio":"Ambientes intermediários e tributários diretos de ambiente lêntico","referencia":"Art. 16, II; Tabela III"},
  {"nome":"Fósforo total — ambiente lótico","unidade":"mg/L P","maximo":0.15,"categoria":"Biológicos e nutrientes","referencia":"Art. 16, II; Tabela III"},
  {"nome":"Lítio total","unidade":"mg/L Li","maximo":2.5,"categoria":"Inorgânicos","referencia":"Art. 16, II; Tabela III"},
  {"nome":"Manganês total","unidade":"mg/L Mn","maximo":0.5,"categoria":"Inorgânicos","referencia":"Art. 16, II; Tabela III"},
  {"nome":"Mercúrio total","unidade":"mg/L Hg","maximo":0.002,"categoria":"Inorgânicos","referencia":"Art. 16, II; Tabela III"},
  {"nome":"Níquel total","unidade":"mg/L Ni","maximo":0.025,"categoria":"Inorgânicos","referencia":"Art. 16, II; Tabela III"},
  {"nome":"Nitrato","unidade":"mg/L N","maximo":10,"categoria":"Biológicos e nutrientes","referencia":"Art. 16, II; Tabela III"},
  {"nome":"Nitrito","unidade":"mg/L N","maximo":1,"categoria":"Biológicos e nutrientes","referencia":"Art. 16, II; Tabela III"},
  {"nome":"Nitrogênio amoniacal total — pH ≤ 7,5","unidade":"mg/L N","maximo":13.3,"categoria":"Biológicos e nutrientes","referencia":"Art. 16, II; Tabela III"},
  {"nome":"Nitrogênio amoniacal total — 7,5 < pH ≤ 8,0","unidade":"mg/L N","maximo":5.6,"categoria":"Biológicos e nutrientes","referencia":"Art. 16, II; Tabela III"},
  {"nome":"Nitrogênio amoniacal total — 8,0 < pH ≤ 8,5","unidade":"mg/L N","maximo":2.2,"categoria":"Biológicos e nutrientes","referencia":"Art. 16, II; Tabela III"},
  {"nome":"Nitrogênio amoniacal total — pH > 8,5","unidade":"mg/L N","maximo":1,"categoria":"Biológicos e nutrientes","referencia":"Art. 16, II; Tabela III"},
  {"nome":"Prata total","unidade":"mg/L Ag","maximo":0.05,"categoria":"Inorgânicos","referencia":"Art. 16, II; Tabela III"},
  {"nome":"Selênio total","unidade":"mg/L Se","maximo":0.05,"categoria":"Inorgânicos","referencia":"Art. 16, II; Tabela III"},
  {"nome":"Sulfato total","unidade":"mg/L SO₄","maximo":250,"categoria":"Inorgânicos","referencia":"Art. 16, II; Tabela III"},
  {"nome":"Sulfeto (como H₂S não dissociado)","unidade":"mg/L S","maximo":0.3,"categoria":"Inorgânicos","referencia":"Art. 16, II; Tabela III"},
  {"nome":"Urânio total","unidade":"mg/L U","maximo":0.02,"categoria":"Inorgânicos","referencia":"Art. 16, II; Tabela III"},
  {"nome":"Vanádio total","unidade":"mg/L V","maximo":0.1,"categoria":"Inorgânicos","referencia":"Art. 16, II; Tabela III"},
  {"nome":"Zinco total","unidade":"mg/L Zn","maximo":5,"categoria":"Inorgânicos","referencia":"Art. 16, II; Tabela III"},
  {"nome":"Aldrin + Dieldrin","unidade":"µg/L","maximo":0.03,"categoria":"Orgânicos","referencia":"Art. 16, II; Tabela III"},
  {"nome":"Atrazina","unidade":"µg/L","maximo":2,"categoria":"Orgânicos","referencia":"Art. 16, II; Tabela III"},
  {"nome":"Benzeno","unidade":"mg/L","maximo":0.005,"categoria":"Orgânicos","referencia":"Art. 16, II; Tabela III"},
  {"nome":"Benzo(a)pireno","unidade":"µg/L","maximo":0.7,"categoria":"Orgânicos","referencia":"Art. 16, II; Tabela III"},
  {"nome":"Carbaril","unidade":"µg/L","maximo":70,"categoria":"Orgânicos","referencia":"Art. 16, II; Tabela III"},
  {"nome":"Clordano (cis + trans)","unidade":"µg/L","maximo":0.3,"categoria":"Orgânicos","referencia":"Art. 16, II; Tabela III"},
  {"nome":"2,4-D","unidade":"µg/L","maximo":30,"categoria":"Orgânicos","referencia":"Art. 16, II; Tabela III"},
  {"nome":"DDT (p,p'-DDT + p,p'-DDE + p,p'-DDD)","unidade":"µg/L","maximo":1,"categoria":"Orgânicos","referencia":"Art. 16, II; Tabela III"},
  {"nome":"Demeton (Demeton-O + Demeton-S)","unidade":"µg/L","maximo":14,"categoria":"Orgânicos","referencia":"Art. 16, II; Tabela III"},
  {"nome":"1,2-Dicloroetano","unidade":"mg/L","maximo":0.01,"categoria":"Orgânicos","referencia":"Art. 16, II; Tabela III"},
  {"nome":"1,1-Dicloroeteno","unidade":"µg/L","maximo":30,"categoria":"Orgânicos","referencia":"Art. 16, II; Tabela III"},
  {"nome":"Dodecacloro pentaciclodecano","unidade":"µg/L","maximo":0.001,"categoria":"Orgânicos","referencia":"Art. 16, II; Tabela III"},
  {"nome":"Endossulfan (α + β + sulfato)","unidade":"µg/L","maximo":0.22,"categoria":"Orgânicos","referencia":"Art. 16, II; Tabela III"},
  {"nome":"Endrin","unidade":"µg/L","maximo":0.2,"categoria":"Orgânicos","referencia":"Art. 16, II; Tabela III"},
  {"nome":"Fenóis totais (4-aminoantipirina)","unidade":"mg/L C₆H₅OH","maximo":0.01,"categoria":"Orgânicos","referencia":"Art. 16, II; Tabela III"},
  {"nome":"Glifosato","unidade":"µg/L","maximo":280,"categoria":"Orgânicos","referencia":"Art. 16, II; Tabela III"},
  {"nome":"Gution","unidade":"µg/L","maximo":0.005,"categoria":"Orgânicos","referencia":"Art. 16, II; Tabela III"},
  {"nome":"Heptacloro epóxido + Heptacloro","unidade":"µg/L","maximo":0.03,"categoria":"Orgânicos","referencia":"Art. 16, II; Tabela III"},
  {"nome":"Lindano (γ-HCH)","unidade":"µg/L","maximo":2,"categoria":"Orgânicos","referencia":"Art. 16, II; Tabela III"},
  {"nome":"Malation","unidade":"µg/L","maximo":100,"categoria":"Orgânicos","referencia":"Art. 16, II; Tabela III"},
  {"nome":"Metoxicloro","unidade":"µg/L","maximo":20,"categoria":"Orgânicos","referencia":"Art. 16, II; Tabela III"},
  {"nome":"Paration","unidade":"µg/L","maximo":35,"categoria":"Orgânicos","referencia":"Art. 16, II; Tabela III"},
  {"nome":"PCBs — Bifenilas policloradas","unidade":"µg/L","maximo":0.001,"categoria":"Orgânicos","referencia":"Art. 16, II; Tabela III"},
  {"nome":"Pentaclorofenol","unidade":"mg/L","maximo":0.009,"categoria":"Orgânicos","referencia":"Art. 16, II; Tabela III"},
  {"nome":"Substâncias tensoativas que reagem com azul de metileno","unidade":"mg/L LAS","maximo":0.5,"categoria":"Orgânicos","referencia":"Art. 16, II; Tabela III"},
  {"nome":"2,4,5-T","unidade":"µg/L","maximo":2,"categoria":"Orgânicos","referencia":"Art. 16, II; Tabela III"},
  {"nome":"Tetracloreto de carbono","unidade":"mg/L","maximo":0.003,"categoria":"Orgânicos","referencia":"Art. 16, II; Tabela III"},
  {"nome":"Tetracloroeteno","unidade":"mg/L","maximo":0.01,"categoria":"Orgânicos","referencia":"Art. 16, II; Tabela III"},
  {"nome":"Toxafeno","unidade":"µg/L","maximo":0.21,"categoria":"Orgânicos","referencia":"Art. 16, II; Tabela III"},
  {"nome":"2,4,5-TP","unidade":"µg/L","maximo":10,"categoria":"Orgânicos","referencia":"Art. 16, II; Tabela III"},
  {"nome":"Tributilestanho","unidade":"µg/L TBT","maximo":2,"categoria":"Orgânicos","referencia":"Art. 16, II; Tabela III"},
  {"nome":"Tricloroeteno","unidade":"mg/L","maximo":0.03,"categoria":"Orgânicos","referencia":"Art. 16, II; Tabela III"},
  {"nome":"2,4,6-Triclorofenol","unidade":"mg/L","maximo":0.01,"categoria":"Orgânicos","referencia":"Art. 16, II; Tabela III"}
]
$json$::jsonb);

select pg_temp.add_legal_params('C357_DOCE_4', $json$
[
  {"nome":"Materiais flutuantes, inclusive espumas não naturais","unidade":"Presença/ausência","categoria":"Condições de qualidade","tipo_resultado":"qualitativo","tipo_limite":"ausencia","criterio":"Virtualmente ausentes","referencia":"Art. 17, I"},
  {"nome":"Odor e aspecto","unidade":"Presença/ausência","categoria":"Condições de qualidade","tipo_resultado":"qualitativo","tipo_limite":"ausencia","criterio":"Não objetáveis","referencia":"Art. 17, II"},
  {"nome":"Óleos e graxas","unidade":"Presença/ausência","categoria":"Condições de qualidade","tipo_resultado":"qualitativo","tipo_limite":"ausencia","criterio":"Toleram-se iridescências","referencia":"Art. 17, III"},
  {"nome":"Fenóis totais (4-aminoantipirina)","unidade":"mg/L C₆H₅OH","maximo":1,"categoria":"Orgânicos","referencia":"Art. 17, IV"},
  {"nome":"Oxigênio dissolvido","unidade":"mg/L O₂","minimo":2,"categoria":"Condições de qualidade","tipo_limite":"minimo","referencia":"Art. 17, V"},
  {"nome":"pH","unidade":"unidade de pH","minimo":6,"maximo":9,"categoria":"Condições de qualidade","referencia":"Art. 17, VI"}
]
$json$::jsonb);


-- Resolução CONAMA nº 357/2005 — águas doces, classe 1.
select pg_temp.add_legal_params('C357_DOCE_1', $json$
[
  {"nome":"Materiais flutuantes, inclusive espumas não naturais","unidade":"Presença/ausência","categoria":"Condições de qualidade","tipo_resultado":"qualitativo","tipo_limite":"ausencia","criterio":"Virtualmente ausentes","referencia":"Art. 14, I, b"},
  {"nome":"Óleos e graxas","unidade":"Presença/ausência","categoria":"Condições de qualidade","tipo_resultado":"qualitativo","tipo_limite":"ausencia","criterio":"Virtualmente ausentes","referencia":"Art. 14, I, c"},
  {"nome":"Substâncias que comuniquem gosto ou odor","unidade":"Presença/ausência","categoria":"Condições de qualidade","tipo_resultado":"qualitativo","tipo_limite":"ausencia","criterio":"Virtualmente ausentes","referencia":"Art. 14, I, d"},
  {"nome":"Corantes provenientes de fontes antrópicas","unidade":"Presença/ausência","categoria":"Condições de qualidade","tipo_resultado":"qualitativo","tipo_limite":"ausencia","criterio":"Virtualmente ausentes","referencia":"Art. 14, I, e"},
  {"nome":"Resíduos sólidos objetáveis","unidade":"Presença/ausência","categoria":"Condições de qualidade","tipo_resultado":"qualitativo","tipo_limite":"ausencia","criterio":"Virtualmente ausentes","referencia":"Art. 14, I, f"},
  {"nome":"Coliformes termotolerantes — demais usos","unidade":"NMP/100 mL","maximo":200,"categoria":"Microbiológicos","criterio":"Não exceder em 80% ou mais de pelo menos 6 amostras anuais, com frequência bimestral; recreação primária segue a CONAMA 274/2000","referencia":"Art. 14, I, g"},
  {"nome":"DBO 5 dias, 20 °C","unidade":"mg/L O₂","maximo":3,"categoria":"Condições de qualidade","referencia":"Art. 14, I, h"},
  {"nome":"Oxigênio dissolvido","unidade":"mg/L O₂","minimo":6,"categoria":"Condições de qualidade","tipo_limite":"minimo","referencia":"Art. 14, I, i"},
  {"nome":"Turbidez","unidade":"UNT","maximo":40,"categoria":"Condições de qualidade","referencia":"Art. 14, I, j"},
  {"nome":"Cor verdadeira","unidade":"mg Pt/L","categoria":"Condições de qualidade","tipo_limite":"informativo","criterio":"Nível de cor natural do corpo de água","referencia":"Art. 14, I, l"},
  {"nome":"pH","unidade":"unidade de pH","minimo":6,"maximo":9,"categoria":"Condições de qualidade","referencia":"Art. 14, I, m"},
  {"nome":"Nitrogênio total — ambiente lêntico (quando limitante)","unidade":"mg/L","maximo":1.27,"categoria":"Nutrientes","criterio":"Aplicável quando o nitrogênio for fator limitante para eutrofização","referencia":"Art. 10, § 3º"},
  {"nome":"Nitrogênio total — ambiente lótico (quando limitante)","unidade":"mg/L","maximo":2.18,"categoria":"Nutrientes","criterio":"Aplicável quando o nitrogênio for fator limitante para eutrofização","referencia":"Art. 10, § 3º"},
  {"nome":"Clorofila a","unidade":"µg/L","maximo":10,"categoria":"Biológicos e nutrientes","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Densidade de cianobactérias","unidade":"células/mL","maximo":20000,"categoria":"Biológicos e nutrientes","criterio":"Alternativamente, até 2 mm³/L de biovolume","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Sólidos dissolvidos totais","unidade":"mg/L","maximo":500,"categoria":"Inorgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Alumínio dissolvido","unidade":"mg/L Al","maximo":0.1,"categoria":"Inorgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Antimônio","unidade":"mg/L Sb","maximo":0.005,"categoria":"Inorgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Arsênio total","unidade":"mg/L As","maximo":0.01,"categoria":"Inorgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Bário total","unidade":"mg/L Ba","maximo":0.7,"categoria":"Inorgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Berílio total","unidade":"mg/L Be","maximo":0.04,"categoria":"Inorgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Boro total","unidade":"mg/L B","maximo":0.5,"categoria":"Inorgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Cádmio total","unidade":"mg/L Cd","maximo":0.001,"categoria":"Inorgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Chumbo total","unidade":"mg/L Pb","maximo":0.01,"categoria":"Inorgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Cianeto livre","unidade":"mg/L CN","maximo":0.005,"categoria":"Inorgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Cloreto total","unidade":"mg/L Cl","maximo":250,"categoria":"Inorgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Cloro residual total (combinado + livre)","unidade":"mg/L Cl","maximo":0.01,"categoria":"Inorgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Cobalto total","unidade":"mg/L Co","maximo":0.05,"categoria":"Inorgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Cobre dissolvido","unidade":"mg/L Cu","maximo":0.009,"categoria":"Inorgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Cromo total","unidade":"mg/L Cr","maximo":0.05,"categoria":"Inorgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Ferro dissolvido","unidade":"mg/L Fe","maximo":0.3,"categoria":"Inorgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Fluoreto total","unidade":"mg/L F","maximo":1.4,"categoria":"Inorgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Fósforo total — ambiente lêntico","unidade":"mg/L P","maximo":0.02,"categoria":"Biológicos e nutrientes","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Fósforo total — ambiente intermediário","unidade":"mg/L P","maximo":0.025,"categoria":"Biológicos e nutrientes","criterio":"Ambientes intermediários e tributários diretos de ambiente lêntico","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Fósforo total — ambiente lótico","unidade":"mg/L P","maximo":0.1,"categoria":"Biológicos e nutrientes","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Lítio total","unidade":"mg/L Li","maximo":2.5,"categoria":"Inorgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Manganês total","unidade":"mg/L Mn","maximo":0.1,"categoria":"Inorgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Mercúrio total","unidade":"mg/L Hg","maximo":0.0002,"categoria":"Inorgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Níquel total","unidade":"mg/L Ni","maximo":0.025,"categoria":"Inorgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Nitrato","unidade":"mg/L N","maximo":10,"categoria":"Biológicos e nutrientes","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Nitrito","unidade":"mg/L N","maximo":1,"categoria":"Biológicos e nutrientes","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Nitrogênio amoniacal total — pH ≤ 7,5","unidade":"mg/L N","maximo":3.7,"categoria":"Biológicos e nutrientes","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Nitrogênio amoniacal total — 7,5 < pH ≤ 8,0","unidade":"mg/L N","maximo":2,"categoria":"Biológicos e nutrientes","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Nitrogênio amoniacal total — 8,0 < pH ≤ 8,5","unidade":"mg/L N","maximo":1,"categoria":"Biológicos e nutrientes","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Nitrogênio amoniacal total — pH > 8,5","unidade":"mg/L N","maximo":0.5,"categoria":"Biológicos e nutrientes","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Prata total","unidade":"mg/L Ag","maximo":0.01,"categoria":"Inorgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Selênio total","unidade":"mg/L Se","maximo":0.01,"categoria":"Inorgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Sulfato total","unidade":"mg/L SO₄","maximo":250,"categoria":"Inorgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Sulfeto (como H₂S não dissociado)","unidade":"mg/L S","maximo":0.002,"categoria":"Inorgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Urânio total","unidade":"mg/L U","maximo":0.02,"categoria":"Inorgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Vanádio total","unidade":"mg/L V","maximo":0.1,"categoria":"Inorgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Zinco total","unidade":"mg/L Zn","maximo":0.18,"categoria":"Inorgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Acrilamida","unidade":"µg/L","maximo":0.5,"categoria":"Orgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Alacloro","unidade":"µg/L","maximo":20,"categoria":"Orgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Aldrin + Dieldrin","unidade":"µg/L","maximo":0.005,"categoria":"Orgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Atrazina","unidade":"µg/L","maximo":2,"categoria":"Orgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Benzeno","unidade":"mg/L","maximo":0.005,"categoria":"Orgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Benzidina","unidade":"µg/L","maximo":0.001,"categoria":"Orgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Benzo(a)antraceno","unidade":"µg/L","maximo":0.05,"categoria":"Orgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Benzo(a)pireno","unidade":"µg/L","maximo":0.05,"categoria":"Orgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Benzo(b)fluoranteno","unidade":"µg/L","maximo":0.05,"categoria":"Orgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Benzo(k)fluoranteno","unidade":"µg/L","maximo":0.05,"categoria":"Orgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Carbaril","unidade":"µg/L","maximo":0.02,"categoria":"Orgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Clordano (cis + trans)","unidade":"µg/L","maximo":0.04,"categoria":"Orgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"2-Clorofenol","unidade":"µg/L","maximo":0.1,"categoria":"Orgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Criseno","unidade":"µg/L","maximo":0.05,"categoria":"Orgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"2,4-D","unidade":"µg/L","maximo":4,"categoria":"Orgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Demeton (Demeton-O + Demeton-S)","unidade":"µg/L","maximo":0.1,"categoria":"Orgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Dibenzo(a,h)antraceno","unidade":"µg/L","maximo":0.05,"categoria":"Orgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"1,2-Dicloroetano","unidade":"mg/L","maximo":0.01,"categoria":"Orgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"1,1-Dicloroeteno","unidade":"mg/L","maximo":0.003,"categoria":"Orgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"2,4-Diclorofenol","unidade":"µg/L","maximo":0.3,"categoria":"Orgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Diclorometano","unidade":"mg/L","maximo":0.02,"categoria":"Orgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"DDT (p,p'-DDT + p,p'-DDE + p,p'-DDD)","unidade":"µg/L","maximo":0.002,"categoria":"Orgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Dodecacloro pentaciclodecano","unidade":"µg/L","maximo":0.001,"categoria":"Orgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Endossulfan (α + β + sulfato)","unidade":"µg/L","maximo":0.056,"categoria":"Orgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Endrin","unidade":"µg/L","maximo":0.004,"categoria":"Orgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Estireno","unidade":"mg/L","maximo":0.02,"categoria":"Orgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Etilbenzeno","unidade":"µg/L","maximo":90,"categoria":"Orgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Fenóis totais (4-aminoantipirina)","unidade":"mg/L C₆H₅OH","maximo":0.003,"categoria":"Orgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Glifosato","unidade":"µg/L","maximo":65,"categoria":"Orgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Gution","unidade":"µg/L","maximo":0.005,"categoria":"Orgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Heptacloro epóxido + Heptacloro","unidade":"µg/L","maximo":0.01,"categoria":"Orgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Hexaclorobenzeno","unidade":"µg/L","maximo":0.0065,"categoria":"Orgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Indeno(1,2,3-cd)pireno","unidade":"µg/L","maximo":0.05,"categoria":"Orgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Lindano (γ-HCH)","unidade":"µg/L","maximo":0.02,"categoria":"Orgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Malation","unidade":"µg/L","maximo":0.1,"categoria":"Orgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Metolacloro","unidade":"µg/L","maximo":10,"categoria":"Orgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Metoxicloro","unidade":"µg/L","maximo":0.03,"categoria":"Orgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Paration","unidade":"µg/L","maximo":0.04,"categoria":"Orgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"PCBs — Bifenilas policloradas","unidade":"µg/L","maximo":0.001,"categoria":"Orgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Pentaclorofenol","unidade":"mg/L","maximo":0.009,"categoria":"Orgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Simazina","unidade":"µg/L","maximo":2,"categoria":"Orgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Substâncias tensoativas que reagem com azul de metileno","unidade":"mg/L LAS","maximo":0.5,"categoria":"Orgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"2,4,5-T","unidade":"µg/L","maximo":2,"categoria":"Orgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Tetracloreto de carbono","unidade":"mg/L","maximo":0.002,"categoria":"Orgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Tetracloroeteno","unidade":"mg/L","maximo":0.01,"categoria":"Orgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Tolueno","unidade":"µg/L","maximo":2,"categoria":"Orgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Toxafeno","unidade":"µg/L","maximo":0.01,"categoria":"Orgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"2,4,5-TP","unidade":"µg/L","maximo":10,"categoria":"Orgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Tributilestanho","unidade":"µg/L TBT","maximo":0.063,"categoria":"Orgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Triclorobenzeno (1,2,3-TCB + 1,2,4-TCB)","unidade":"mg/L","maximo":0.02,"categoria":"Orgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Tricloroeteno","unidade":"mg/L","maximo":0.03,"categoria":"Orgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"2,4,6-Triclorofenol","unidade":"mg/L","maximo":0.01,"categoria":"Orgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Trifluralina","unidade":"µg/L","maximo":0.2,"categoria":"Orgânicos","referencia":"Art. 14, II; Tabela I"},
  {"nome":"Xileno","unidade":"µg/L","maximo":300,"categoria":"Orgânicos","referencia":"Art. 14, II; Tabela I"}
]
$json$::jsonb);


-- Resolução CONAMA nº 430/2011.
select pg_temp.add_legal_params('C430_GERAL', $json$
[
  {"nome":"pH","unidade":"unidade de pH","minimo":5,"maximo":9,"categoria":"Condições gerais","referencia":"Art. 16, I, a"},
  {"nome":"Temperatura do efluente","unidade":"°C","maximo":40,"categoria":"Condições gerais","criterio":"Inferior a 40 °C","referencia":"Art. 16, I, b"},
  {"nome":"Variação de temperatura do corpo receptor","unidade":"°C","maximo":3,"categoria":"Condições gerais","criterio":"No limite da zona de mistura","referencia":"Art. 16, I, b"},
  {"nome":"Materiais sedimentáveis","unidade":"mL/L","maximo":1,"categoria":"Condições gerais","criterio":"Teste de 1 hora em cone Imhoff; em lagos e lagoas com circulação praticamente nula devem estar virtualmente ausentes","referencia":"Art. 16, I, c"},
  {"nome":"Vazão máxima instantânea em relação à média diária","unidade":"%","maximo":150,"categoria":"Condições gerais","criterio":"Até 1,5 vez a vazão média do período de atividade diária, salvo autorização competente","referencia":"Art. 16, I, d"},
  {"nome":"Óleos minerais","unidade":"mg/L","maximo":20,"categoria":"Óleos e graxas","referencia":"Art. 16, I, e, 1"},
  {"nome":"Óleos vegetais e gorduras animais","unidade":"mg/L","maximo":50,"categoria":"Óleos e graxas","referencia":"Art. 16, I, e, 2"},
  {"nome":"Materiais flutuantes","unidade":"Presença/ausência","categoria":"Condições gerais","tipo_resultado":"qualitativo","tipo_limite":"ausencia","criterio":"Ausência","referencia":"Art. 16, I, f"},
  {"nome":"Eficiência de remoção de DBO 5 dias, 20 °C","unidade":"%","minimo":60,"categoria":"Condições gerais","tipo_limite":"minimo","criterio":"Remoção mínima; redução somente mediante estudo de autodepuração que comprove o enquadramento","referencia":"Art. 16, I, g"},
  {"nome":"Arsênio total","unidade":"mg/L As","maximo":0.5,"categoria":"Inorgânicos","referencia":"Art. 16, II; Tabela I"},
  {"nome":"Bário total","unidade":"mg/L Ba","maximo":5,"categoria":"Inorgânicos","referencia":"Art. 16, II; Tabela I"},
  {"nome":"Boro total","unidade":"mg/L B","maximo":5,"categoria":"Inorgânicos","criterio":"Não se aplica ao lançamento em águas salinas","referencia":"Art. 16, II; Tabela I"},
  {"nome":"Cádmio total","unidade":"mg/L Cd","maximo":0.2,"categoria":"Inorgânicos","referencia":"Art. 16, II; Tabela I"},
  {"nome":"Chumbo total","unidade":"mg/L Pb","maximo":0.5,"categoria":"Inorgânicos","referencia":"Art. 16, II; Tabela I"},
  {"nome":"Cianeto total","unidade":"mg/L CN","maximo":1,"categoria":"Inorgânicos","referencia":"Art. 16, II; Tabela I"},
  {"nome":"Cianeto livre (destilável por ácidos fracos)","unidade":"mg/L CN","maximo":0.2,"categoria":"Inorgânicos","referencia":"Art. 16, II; Tabela I"},
  {"nome":"Cobre dissolvido","unidade":"mg/L Cu","maximo":1,"categoria":"Inorgânicos","referencia":"Art. 16, II; Tabela I"},
  {"nome":"Cromo hexavalente","unidade":"mg/L Cr⁶⁺","maximo":0.1,"categoria":"Inorgânicos","referencia":"Art. 16, II; Tabela I"},
  {"nome":"Cromo trivalente","unidade":"mg/L Cr³⁺","maximo":1,"categoria":"Inorgânicos","referencia":"Art. 16, II; Tabela I"},
  {"nome":"Estanho total","unidade":"mg/L Sn","maximo":4,"categoria":"Inorgânicos","referencia":"Art. 16, II; Tabela I"},
  {"nome":"Ferro dissolvido","unidade":"mg/L Fe","maximo":15,"categoria":"Inorgânicos","referencia":"Art. 16, II; Tabela I"},
  {"nome":"Fluoreto total","unidade":"mg/L F","maximo":10,"categoria":"Inorgânicos","referencia":"Art. 16, II; Tabela I"},
  {"nome":"Manganês dissolvido","unidade":"mg/L Mn","maximo":1,"categoria":"Inorgânicos","referencia":"Art. 16, II; Tabela I"},
  {"nome":"Mercúrio total","unidade":"mg/L Hg","maximo":0.01,"categoria":"Inorgânicos","referencia":"Art. 16, II; Tabela I"},
  {"nome":"Níquel total","unidade":"mg/L Ni","maximo":2,"categoria":"Inorgânicos","referencia":"Art. 16, II; Tabela I"},
  {"nome":"Nitrogênio amoniacal total","unidade":"mg/L N","maximo":20,"categoria":"Inorgânicos","referencia":"Art. 16, II; Tabela I"},
  {"nome":"Prata total","unidade":"mg/L Ag","maximo":0.1,"categoria":"Inorgânicos","referencia":"Art. 16, II; Tabela I"},
  {"nome":"Selênio total","unidade":"mg/L Se","maximo":0.3,"categoria":"Inorgânicos","referencia":"Art. 16, II; Tabela I"},
  {"nome":"Sulfeto","unidade":"mg/L S","maximo":1,"categoria":"Inorgânicos","referencia":"Art. 16, II; Tabela I"},
  {"nome":"Zinco total","unidade":"mg/L Zn","maximo":5,"categoria":"Inorgânicos","referencia":"Art. 16, II; Tabela I"},
  {"nome":"Benzeno","unidade":"mg/L","maximo":1.2,"categoria":"Orgânicos","referencia":"Art. 16, II; Tabela I"},
  {"nome":"Clorofórmio","unidade":"mg/L","maximo":1,"categoria":"Orgânicos","referencia":"Art. 16, II; Tabela I"},
  {"nome":"Dicloroeteno (soma de 1,1 + 1,2-cis + 1,2-trans)","unidade":"mg/L","maximo":1,"categoria":"Orgânicos","referencia":"Art. 16, II; Tabela I"},
  {"nome":"Estireno","unidade":"mg/L","maximo":0.07,"categoria":"Orgânicos","referencia":"Art. 16, II; Tabela I"},
  {"nome":"Etilbenzeno","unidade":"mg/L","maximo":0.84,"categoria":"Orgânicos","referencia":"Art. 16, II; Tabela I"},
  {"nome":"Fenóis totais (4-aminoantipirina)","unidade":"mg/L C₆H₅OH","maximo":0.5,"categoria":"Orgânicos","referencia":"Art. 16, II; Tabela I"},
  {"nome":"Tetracloreto de carbono","unidade":"mg/L","maximo":1,"categoria":"Orgânicos","referencia":"Art. 16, II; Tabela I"},
  {"nome":"Tricloroeteno","unidade":"mg/L","maximo":1,"categoria":"Orgânicos","referencia":"Art. 16, II; Tabela I"},
  {"nome":"Tolueno","unidade":"mg/L","maximo":1.2,"categoria":"Orgânicos","referencia":"Art. 16, II; Tabela I"},
  {"nome":"Xileno","unidade":"mg/L","maximo":1.6,"categoria":"Orgânicos","referencia":"Art. 16, II; Tabela I"}
]
$json$::jsonb);

select pg_temp.add_legal_params('C430_ESGOTO_SANITARIO', $json$
[
  {"nome":"pH","unidade":"unidade de pH","minimo":5,"maximo":9,"categoria":"Condições específicas","referencia":"Art. 21, I, a"},
  {"nome":"Temperatura do efluente","unidade":"°C","maximo":40,"categoria":"Condições específicas","criterio":"Inferior a 40 °C","referencia":"Art. 21, I, b"},
  {"nome":"Variação de temperatura do corpo receptor","unidade":"°C","maximo":3,"categoria":"Condições específicas","criterio":"No limite da zona de mistura","referencia":"Art. 21, I, b"},
  {"nome":"Materiais sedimentáveis","unidade":"mL/L","maximo":1,"categoria":"Condições específicas","criterio":"Teste de 1 hora em cone Imhoff; em lagos e lagoas com circulação praticamente nula devem estar virtualmente ausentes","referencia":"Art. 21, I, c"},
  {"nome":"DBO 5 dias, 20 °C","unidade":"mg/L","maximo":120,"categoria":"Condições específicas","criterio":"O limite pode ser ultrapassado com eficiência mínima de remoção de 60% ou estudo de autodepuração aceito","referencia":"Art. 21, I, d"},
  {"nome":"Eficiência de remoção de DBO 5 dias, 20 °C","unidade":"%","minimo":60,"categoria":"Condições específicas","tipo_limite":"minimo","criterio":"Critério alternativo ao VMP de 120 mg/L","referencia":"Art. 21, I, d"},
  {"nome":"Substâncias solúveis em hexano (óleos e graxas)","unidade":"mg/L","maximo":100,"categoria":"Condições específicas","referencia":"Art. 21, I, e"},
  {"nome":"Materiais flutuantes","unidade":"Presença/ausência","categoria":"Condições específicas","tipo_resultado":"qualitativo","tipo_limite":"ausencia","criterio":"Ausência","referencia":"Art. 21, I, f"}
]
$json$::jsonb);

select pg_temp.add_legal_params('C430_EMISSARIO_SUBMARINO', $json$
[
  {"nome":"pH","unidade":"unidade de pH","minimo":5,"maximo":9,"categoria":"Condições específicas","referencia":"Art. 22, parágrafo único, I"},
  {"nome":"Temperatura do efluente","unidade":"°C","maximo":40,"categoria":"Condições específicas","criterio":"Inferior a 40 °C","referencia":"Art. 22, parágrafo único, II"},
  {"nome":"Variação de temperatura do corpo receptor","unidade":"°C","maximo":3,"categoria":"Condições específicas","criterio":"No limite da zona de mistura","referencia":"Art. 22, parágrafo único, II"},
  {"nome":"Sólidos grosseiros e materiais flutuantes","unidade":"Presença/ausência","categoria":"Condições específicas","tipo_resultado":"qualitativo","tipo_limite":"ausencia","criterio":"Virtualmente ausentes, após desarenação","referencia":"Art. 22, parágrafo único, III e IV"},
  {"nome":"Eficiência de remoção de sólidos em suspensão totais","unidade":"%","minimo":20,"categoria":"Condições específicas","tipo_limite":"minimo","criterio":"Eficiência mínima após desarenação","referencia":"Art. 22, parágrafo único, V"}
]
$json$::jsonb);

-- Algumas classes herdam integralmente a classe anterior, com as exceções
-- já registradas acima. Esta etapa final materializa os itens herdados sem
-- sobrescrever os limites específicos de cada contexto.
select pg_temp.clone_legal_params('C357_DOCE_1', 'C357_DOCE_1_AQUICULTURA');
select pg_temp.clone_legal_params('C357_DOCE_1', 'C357_DOCE_2');
select pg_temp.clone_legal_params('C357_SALINA_1', 'C357_SALINA_1_AQUICULTURA');
select pg_temp.clone_legal_params('C357_SALINA_1', 'C357_SALINA_2');
select pg_temp.clone_legal_params('C357_SALINA_1', 'C357_SALOBRA_1');

delete from public.parametro p
using public.legislacao_contexto c
where p.contexto_legislacao_id = c.id
  and c.codigo = 'C357_SALOBRA_1'
  and p.nome in ('Bário total', 'Tálio total', 'Urânio total');

select pg_temp.clone_legal_params('C357_SALOBRA_1', 'C357_SALOBRA_1_AQUICULTURA');
select pg_temp.clone_legal_params('C357_SALOBRA_1', 'C357_SALOBRA_2');

delete from public.parametro p
using public.legislacao_contexto c
where p.contexto_legislacao_id = c.id
  and c.codigo in ('C357_SALOBRA_1_AQUICULTURA', 'C357_SALOBRA_2')
  and p.nome in ('Bário total', 'Tálio total', 'Urânio total');

commit;
